### ISSUE TITLE
Versions.json Deprecation

### ISSUE THREAD

**Issue by zanix** [MinecraftServerControl/mscs#117]
I just downloaded `versions.json` to answer another issue and there is a nice message in the file.

> "__comment": "This URL is being phased out! Please update your scripts to check https://launchermeta.mojang.com/mc/game/version_manifest.json instead. Thanks <3 --Dinnerbone",

Looks like we need to update the URL and possibly the parsing since they added a url to each version.

```json
  "versions":[
    {
      "id":"1.9-pre1",
      "type":"snapshot",
      "time":"2016-02-17T15:24:11+00:00",
      "releaseTime":"2016-02-17T15:23:19+00:00",
      "url":"https://launchermeta.mojang.com/mc/game/6768033e216468247bd031a0a2d9876d79818f8f/1.9-pre1.json"
    },
    {
      "id":"16w07b",
      "type":"snapshot",
      "time":"2016-02-16T15:23:33+00:00",
      "releaseTime":"2016-02-16T15:22:39+00:00",
      "url":"https://launchermeta.mojang.com/mc/game/6768033e216468247bd031a0a2d9876d79818f8f/16w07b.json"
    },
```

**Comment by sandain** [comment]
Nice find.  I'll take a look at the differences between files and come up with a patch when I have some time.

**Comment by zanix** [comment]
The only difference seems to be the addition of the url for each version. I hope they don't retire the method we use to download the client and server jars as well.

**Comment by sandain** [comment]
It looks like we are going to need to use a real json parser to update to the URL.  I'm currently looking at the [JSON](http://search.cpan.org/~makamaka/JSON-2.90/lib/JSON.pm) package that I already had installed via the package `libjson-perl`.

**Comment by sandain** [comment]
The following code works with both files when checking the latest version:
```
perl -0777ne 'use JSON; $json = decode_json ($_); print $json->{latest}{release};' versions.json
```
I'll check the other places where the versions.json file is read and update this comment.

The nice thing about using the JSON library instead of a regex is that the code becomes much more readable, which is always nice.

**Comment by zanix** [comment]
Nice, do you think you can also use this library to output the server info for the `query-json` command and the `tellraw` command in the `overviewer()` function

**Comment by sandain** [comment]
The library also has a method called `encode_json`, so yeah.  Although I'm not sure how useful it would be to bring Perl into the equation for the query-json and tellraw command in the overviewer function.  The current text would have to be converted into a Perl data structure.

**Comment by zanix** [comment]
Ah, makes sense. I think for more complex output it would be useful, like for REST services. I still need to write up a REST issue sometime.

**Comment by sandain** [comment]
The two regex were replaced with code similar to the comment above with commit 1c11172aa9f891b6638fb82706c08ea4411c27da.  The new URL is now used with commit 5d43ae8d0ec4353c67d1e453d94766dd839204cd.  Issue closed.

**Comment by zanix** [comment]
Does the required software list need to be updated to add `libjson-perl` for those systems that may not already have it?

**Comment by sandain** [comment]
README was updated.  Did I miss somewhere else?

**Comment by zanix** [comment]
Ah, I didn't see `README.md` in the commit log, my bad.
