### ISSUE TITLE
Add an optional GUI

### ISSUE THREAD

**Issue by sandain** [MinecraftServerControl/mscs#118]
A lot of discussion on adding an optional GUI has taken place on a closed issue starting [here](https://github.com/sandain/MinecraftServerControlScript/issues/113#issuecomment-184969253).  Let's move the discussion into a new thread.

To sum up, a lot of different options were listed, but Java or web based (html/javascript or php/perl/python) seem to make the most sense.

# Java
control remote host running mscs from any platform with Java
requires ssh, but Java might have a built in mechanism.
 -- either using a single ssh session per command
 -- or maintain a single ssh session that commands are piped to (see query code).
user security provided by ssh

# Web based
control local host running mscs, provide web page that can be made web accessible
requires a web server
user security provided by web server

# User trust
When using the mscs script, all processes are run by a system user account with limited access (assuming the Makefile was used).  However,  the script must assume that everything fed to it by the user is correct, especially since the script is so modifiable. Fortunatly, since everything is run by a limited system user, we theoretically can't hose the system even if we get a malicious user of the script, the only potential loss is to the mscs data -- including any world data.  A GUI potentially opens more users to access to the script, so I think it would be smart to be careful what kind of user input is accepted (think of how an SQL injection type of hack works).  We will probably need to verify that all strings are quoted in the script, and the sanitation pass in the GUI would have to make sure not to send quote chars, the LF char, and who knows what else.

So anyway, lets continue the discussion here.

**Comment by sandain** [comment]
@Roflicide, no worries.  I'm happy to answer any questions.

> X

X is a dead end.  I see no reason to develop anything that depends on X to function.  Network transparency might make it into Wayland and Mir,  but there are so many other more cross platform ways to do this that I see no reason to go that route.

> xkcd

Exactly.

I like your mockup.  I think Java is a fine language.  If you want me to, I can try to write a class to do the basic communication with the script.  I imagine it would be possible to write something that could handle both a local and a remote install.

**Comment by sandain** [comment]
It looks like [jsch](http://www.jcraft.com/jsch/) is a commonly used Java library that appears to have the functionality needed (look at their [examples](http://www.jcraft.com/jsch/examples/)).

**Comment by Roflicide** [comment]
Good idea starting a new thread

> X is a dead end. I see no reason to develop anything that depends on X to function. Network transparency might make it into Wayland and Mir, but there are so many other more cross platform ways to do this that I see no reason to go that route.

Interesting, I had no idea X was getting phased out. In that case, indeed it wouldn't make sense to make the script dependent on it!

> I like your mockup.

Thanks!

>  If you want me to, I can try to write a class to do the basic communication with the script. I imagine it would be possible to write something that could handle both a local and a remote install.

 _If_ you're feeling up to the task, the basic communication for the GUI would be extremely helpful. Though, I certainly don't want you to feel obligated to complete it. 

> It looks like jsch is a commonly used Java library for ssh that appears to have the functionality needed (look at their examples).

Oo, this looks very nice indeed. I'll be sure to check this out.

**Comment by sandain** [comment]
The first issue that we need to resolve is where this project is going to live.  Do we place it in a subdirectory of this repo (e.g. `gui`), create a new repo on my user (e.g. `mscs-gui`), or create a new repo on your user?  The name of the project is also open to discussion, my working title right now is `mscs-gui`, but I'm open to other ideas (e.g. maybe `mscsGUI` is a better option) that don't necessarily have to do with `mscs` (e.g. `MC Controller`).

**Comment by zanix** [comment]
I would say keep it within your repo.
You could also create an organization to hold these repos as well. As long as this remains open source (using a recognized open source license) it's free.
`mscsGUI` or `mscs-gui` sound good to me. The repo can be called that but the "advertized" name could be different.

**Comment by sandain** [comment]
I was just thinking it could simply be `msc` for Minecraft Server Controller.  Whatever way we go, we need to verify that no one else is using the name or command.

**Comment by galenpospisil** [comment]
Just my two cents: a java-based ui seems to be almost as much of a dead-end as X.  An optional module that adds a web interface to MSCS seems like an excellent way to go from my perspective.  I have used both MSCS and Mine-OS.  The holy grail of minecraft server hosting (which neither project yet provides) is a sensible management interface that is consistent across both the CLI and Web-UI.

**Comment by Roflicide** [comment]
Hi @overcookedTOFU, thanks for taking the time to provide some feedback.

In your eyes, why do you a consider java-based UI to be a dead-end as opposed to a web based UI?

**Comment by overcookedTOFU** [comment]
Hi, sorry to swoop in out of the blue and push back on the java idea.  Thanks for asking for more feedback, I should have been less abrupt the first time around.  I would be the first to admit that I don't know much about developing GUIs in Java but at least for my use case there are two reasons why I would suggest going with a web-ui:

1) A java-ui does not increase the number of devices from which I can manage my minecraft servers.
2) A java-ui will likely require more work to port and maintain on multiple platforms.

I currently run minecraft on a headless box in my house.  Currently I log in via ssh to manage with MSCS.  While a java application running on my workstation could make it easier to manage from that device, it would not let me manage it from any more devices than I can now.  I still need ssh + a platform that supports java to access MSCS.  A web-ui could be accessed via any browser and would greatly expand the number of devices I can manage my minecraft server from.  

While java may make it easier to create a native management front-end for multiple platforms, it will still likely demand tweaking and rewriting for each one.  My understanding is that cross platform java ui remains quite difficult, though I haven't looked at it for a few years.  A web-ui using the right framework would minimize the amount of platform specific code needed.  

Anyhow, I love the UI mockup.  Thanks for creating such a great script!

**Comment by zanix** [comment]
I agree with @overcookedTOFU, a web based GUI would be easier to develop to fit multiple devices.

**Comment by sandain** [comment]
@Nevra [posted](http://www.minecraftforum.net/forums/support/server-support/server-administration/1894314-multi-world-linux-minecraft-server-control-script?comment=85) a walk through where she(?) gets the script working with Apache.  I'm not sure I agree with using the same user to run both the web and minecraft servers, but the method should still work.

**Comment by Roflicide** [comment]
@overcookedTOFU 

> Hi, sorry to swoop in out of the blue and push back on the java idea. 

No worries ;)

> 1) A java-ui does not increase the number of devices from which I can manage my minecraft servers.
2) A java-ui will likely require more work to port and maintain on multiple platforms.

These are both valid points, and I agree that the web-UI approach definitely has its perks. 
However, these are the reasons why I wanted to do Java:

- Personally, I'm only really familiar with Java, so I'd be able to contribute more. =)

- ***Security***. Probably the biggest issue here I think. I tried to lookup on this stuff and I think I got a grasp on it...

@sandain I think I got the stuff right below, if you could verify the below information that'd be awesome :)

From what I understand, there are two ways to authenticate with SSH: public/private key authentication or passwords. The private/public key way is considered more secure since it doesn't actually send a password over the internet like the password method does.

**Password method over web server** 
- Requires a SSL certificate to be secure, that _you_ have to purchase ([Source 1](http://security.stackexchange.com/questions/37392/when-to-use-ssl-when-to-send-passwords-via-mail))
- If that encryption is broken, the attacker will get your password and you can say goodbye to your diamonds
- Typically weak ([Source 2](http://security.stackexchange.com/questions/40050/what-is-the-best-practice-separate-ssh-key-per-host-and-user-vs-one-ssh-key-for))

**Public/private key method over web server**
- Doesn't send a password over internet
- If encryption is broken, no password is revealed
- Very strong, lots of characters
- Downside is you have to store the private key everywhere you want to login ([Source 3](http://security.stackexchange.com/questions/3887/is-using-a-public-key-for-logging-in-to-ssh-any-better-than-saving-a-password))

Clearly, public/private key method is the way to go. But I think this puts more of a burden on the users to store the private key on every computer they use to access the script.

If we decide to do the password way of authentication, then I suppose every user would have to get a SSL cert. if they truly wanted to be secure--but it costs money :(. Also, as @sandain alluded to, I think we would want to make it two different users on the client/web so that in case a hacker gets one credentials he won't get the other.


overall, I agree that the web server would be more convenient than a Java gui since you can access it anywhere, from any device, etc. etc. But i think you also have to weigh in the security  factors, and I think it will require more work. (@sandain what do you think?)

**Comment by sandain** [comment]
I don't have time to fully think about your post right now @Roflicide, but I'll get back to it later this weekend.  I do have one quick comment though:

>Requires a SSL certificate to be secure, that you have to purchase

You can get free SSL certificates [here](https://letsencrypt.org/).

**Comment by BogusCurry** [comment]
A very nice idea ;D I am not a developer, only a "normal" user, but I think that make a many users happy ;D

**Comment by Munsio** [comment]
Why do you not provide an REST API service so you don't have to deal with an strict Java or Web Interface?

In our company we currently setting up an API with [jsonapi](http://jsonapi.org/) it has a wide range on server/client sdks for languages such as PHP, Python, Java, Javascript (Node.js)....
With such an api, probably everyone could make an gui for mscs, and an small api service doesn't need much server resources.

All in all: If you want to make such an service i would recommend to build the server side either in python or java cause python is afaik on every linux installation pre-installed and java is used by minecraft so i don't think i have to explain that.

About security: In general you don't have to buy an ssl certificate cause a self-signed certificate is so secure as one that you buy - the only difference is that the one that you bought is validated by an external service (money maker -.-)

Sry for my bad english :grin:

**Comment by zanix** [comment]
> Why do you not provide an REST API service so you don't have to deal with an strict Java or Web Interface?

Good idea. Then we could have any GUI that is desired.

**Comment by Munsio** [comment]
For authentication you could generate an token with the api service and use an self-signed 4096bit ssl cert - than all you have to say is good luck & have fun in making a man in the middle attack

**Comment by sandain** [comment]
Well I have a custom theme-able html GUI that I wrote in Perl a long time ago for a project that never ending up using it partially working for this purpose.  It is based on CGI::Ajax which may not have been the best choice, but the interface is fast and so far has survived my backwards compatibility tests (it should work on IE6 and lynx, although I haven't tested lynx recently and I have no plans to test IE).  I'll publish the code when it is working a little better and I've written the readme.  The default theme doesn't look anything like @Roflicide's mockup above, but I have no doubt a theme could be written to more closely match it (themes are mainly done via CSS).

Right now I'm not even thinking about how to give the user access to the console or send commands,  and in the readme I'll probably recommend leaving this service open to localhost only, so authentication issues will be minimal to begin with.  However, I'm glad that a number of us are giving this some thought.

CGI::Ajax spits out a security warning every time my demo program is run.  I can hide the warning, but that just seems wrong.  I'm not sure CGI::Ajax is being updated anymore, and there are probably other frameworks that are better (perhaps jsonapi is one such option).  The final product doesn't have to be written in Perl either, I just had the ability to rapidly put together a prototype with code I had in hand.

**Comment by sandain** [comment]
Here is a screen capture of the demo:
![gui-demo](https://cloud.githubusercontent.com/assets/641148/13200869/faedc6f6-d817-11e5-9cbd-8e8c203c56a8.png)

**Comment by Roflicide** [comment]
@sandain Nice! I can't wait to get my hands on it! :D

**Comment by sandain** [comment]
This is prone to change (e.g. the visibility stuff is unused and so far uneeded), but here is the current CSS file for the theme:

```
body {
  font-family: 'Comic Sans MS', sans-serif;
  background-color: white;
  width: 100%;
  margin: 0px;
}

a {
  text-decoration: none;
  display: inline-block;
  cursor: pointer;
  color: #000000;
}

a:hover {
  color: #666666;
}

a:active {
  color: #000000;
}

#title_box {
  background-color: #777777;
  position: absolute;
  width: 100%;
  height: 110px;
  left: 0px;
  top: 0px;
  z-index: 0;
}

#title {
  position:absolute;
  height: 110px;
  left: 130px;
  top: 0px;
  margin-top: 15px;
  z-index: 1;
  font-size: 30pt;
  font-weight: bold;
  text-decoration: none;
  text-align: left;
}

#title_image {
  margin: 5px;
}

#menu_box {
  background-color: #444444;
  position: absolute;
  width: 100%;
  height: 30px;
  left: 0px;
  top: 110px;
  margin: 0px;
  z-index: 0;
}

a.menu_item {
  margin-right: 0.5cm;
}

#content_box {
  background-color: #FFFFFF;
  position: absolute;
  width: 100%;
  height: 450px;
  left: 0px;
  top: 140px;
  margin-top: 20px;
  margin: 0px;
  z-index: 0;
  font-size: 11pt;
  text-decoration: none;
  text-align: center;
}

.hidden {
  visibility: hidden;
}

.visible {
  visibility: visible;
}
```
I knew there was something I really hated about the font..  WTF do I have the font set to Comics Sans?!?!

**Comment by Roflicide** [comment]
> comic sans

![image](https://s-media-cache-ak0.pinimg.com/236x/4a/22/ab/4a22ab0e593603475984f109b8b0c6f1.jpg)

**Comment by sandain** [comment]
So I'm trying to figure out the best way to have the Perl GUI talk to the script.  The `mscs` script assumes it is being run by the `minecraft` user or a user with access to sudo while apache uses the user `www-data`.  To get it working on my setup, I gave the apache user full sudo access.  This is not ideal. I think I can lock sudo access down to a single user and command, so I'm going to give that a shot.  Does anyone have a better idea?

**Comment by sandain** [comment]
Here is my entry for the sudoer file:
```
# Allow www-data to execute the msctl command as the minecraft user.
www-data ALL=(minecraft:minecraft) NOPASSWD: /usr/local/bin/msctl
```

That seems to be all that is needed.  In the spirit of KISS, I think this is the answer.  Anyone have any other ideas?

**Comment by sandain** [comment]
New screencap.  The output displayed is the real output from the GUI running `mscs status alpha`:
![screencap](https://cloud.githubusercontent.com/assets/641148/13207518/ab744964-d8cc-11e5-95a4-f9a974344523.png)

**Comment by sandain** [comment]
I just did a code drop [here](https://github.com/MinecraftServerControl/mscGUI) for the new GUI.  The README has no information yet, but I'll try to remedy that has I have time.

**Comment by Roflicide** [comment]
Looks good, I'll be waiting for the install instructions :)

**Comment by sandain** [comment]
Ok, some of the docs are up.  I don't have anything about installing the script because I'm thinking of changing it's design: from 2 .pm files, 1 .pl file, the Build.PL file, and the MANIFEST file to a single monolithic .pl file that can be more easily dealt with. 

For now, the missing section is:

```
./Build.PL
./Build
sudo ./Build install
mkdir /opt/mscs/gui
cp index.pl /opt/mscs/gui
cp -R themes /opt/mscs/gui
sudo ln -s /opt/mscs/gui /var/www/gui
```

or something like that

**Comment by sandain** [comment]
I went ahead and made the change to a single monolithic .pl file.  So now that section will most likely look like:
```
mkdir /opt/mscs/gui
cp index.pl /opt/mscs/gui
cp -R themes /opt/mscs/gui
sudo ln -s /opt/mscs/gui /var/www/gui
```

**Comment by Roflicide** [comment]
Any idea how I would forward the traffic from the server of my remote `localhost` (linux computer) to the `localhost` of my computer (windows)? I thought it had to do with some port forwarding but that didn't work. I'm using the PuTTY ssh client

**Comment by sandain** [comment]
I'm confused on your question I guess.  If you are asking about allowing outside access to the web server, you may need to setup port forwarding on port 80 to the host computer and make sure that port 80 isn't being blocked by a firewall like iptables (the iptables.rules file that I posted has port 80 open).

**Comment by Roflicide** [comment]
Hi @sandain, that was a poorly phrased question, my apologies. 

Bear with me, since I'm not quite sure what I'm doing, but according to my IPtables and this website http://ping.eu/port-chk/ my port 80 is open, which makes sense since I have a website for my server that simply displays the Minecraft overviewer map (so it must be open).

I'm just trying to figure out how to connect to the web interface a) so only I can access the GUI and b) so that I can access it at all. Right now when I navigate to the gui on the website my browser wants to download a perl script and nothing displays.

**Comment by sandain** [comment]
hmm, you probably need to get mod_cgi enabled with something like the following:
```
sudo ln -s /etc/apache2/mods-available/cgi.load /etc/apache2/mods-enabled/cgi.load
sudo systemctl restart apache2
```

**Comment by zanix** [comment]
If you are on Ubuntu you can use these commands

```shell
a2enmod cgi
service apache2 restart
```

**Comment by Roflicide** [comment]
thanks for the help guys, it was actually a configuration issue on my end with the way debian organizes apaches configuration--there's like 6 different folders that all contain different conf files that feed into the main `apache.conf` file, and long story short I didn't realize you can only include one `<VirtualHost>` entry per file so it wasn't reading it correctly.

anyway, I did managed to get something! but it doesn't seem to be displaying worlds:
![](http://i.imgur.com/H33dDPP.png)

could I have mis-configured the permissions or something? my `/etc/sudoers.d/mscs` file looks like the following...

     #Allow www-data to execute the msctl command as the minecraft user.
     www-data ALL=(minecraft:minecraft) NOPASSWD: /usr/local/bin/msctl

**Comment by sandain** [comment]
hmm, that should work.  Is `www-data` and `minecraft` the correct usernames for your install?  Does your `/etc/sudoers` file actually source the files in the `/etc/sudoers.d/` folder?
```
$ sudo tail /etc/sudoers
<snip>
#includedir /etc/sudoers.d
```

**Comment by Roflicide** [comment]
i believe it does:

![](http://i.imgur.com/aQGx2aR.png)

**Comment by JimTR** [comment]
what happens with virtual hosts the user is not www-data but the owner .. I guess this only works on a totaly managed system

**Comment by sandain** [comment]
@Roflicide, I'm not sure why you aren't seeing any worlds.  I'll give this some more thought on my way home.

@JimTR, I'm sure a virtual host system would work just fine.  The directions would be different for sure, but nothing about the program I wrote depends on the user being named `www-data`.

**Comment by JimTR** [comment]
in a VH how would you install ? bear in mind you have no access out of your home ?

**Comment by JimTR** [comment]
Worked it out .... the web script for mscs install should install in the VM users space, this gives the VM user the 'rights' over the files installed ... means no read/write issues.

**Comment by Roflicide** [comment]
@sandain 

Figured it out--absolutely ridiculous: I had to add a newline at the end of the file... That's it. It's funny actually, when I was learning crontab it's also [a known problem](http://askubuntu.com/a/23337) with crontab that you actually have to add a newline at the end of the file, just like I did in the sudoers.d file. Why that is, who knows...

Works like a charm now! :)

**Comment by sandain** [comment]
I'm glad you got it working.

The program functions right now to a very limited extent.  We probably need to introduce a new command to the mscs script to provide raw query data so that we can more cleanly implement the world tabs.  Implementing start/stop/restart functions is where I start worrying about permissions, but it should be technically easy to do at this point.

What were you thinking of for the dashboard?  Does the Perl code make sense?

**Comment by Roflicide** [comment]
Yea, the Perl code looks pretty straightforward. I'll probably gonna need a bit of time to familiarize myself with Perl itself, but I don't think it'll be that hard. 

In terms of the dashboard, I was just thinking of a simple world list.

**Comment by Roflicide** [comment]
@sandain So i was looking over the GUI files, I'm just a bit confused on how all the files are connected. I see the css file and different Xhtml files, but I don't see where the actual html/xhtml file of the layout of the page is.

**Comment by sandain** [comment]
The three xhtml files (`header.xhtml`, `body.xhtml`, and `footer.xhtml`) get read in with any macros (in the form of `<?msc_xhtml_title?>` for the title) replaced with generated content.  Line  111 and 122 of `index.pl` are where the macros are defined in the hash called `tags`.

The actual content that is displayed for each world is currently defined in the `create_world_content` method of `index.pl`.  It probably makes sense to pull this out into its own xhtml file and add more macros to `tags` to allow for more the theming options.  The dashboard is in a similar situation, defined by the method `create_dashboard_content`.

The menu for the `<?msc_xhtml_menu?>` macro is put together in the `create_menu_content` method.  If you look closely at this method, particularly how the links are done, you can see how I have made this functional with or without javascript.

The main content for the `<?msc_xhtml_content?>` macro is done in the `create_main_content` method.  The content displayed at load time is either defined in CGI vars (no javascript) or defaults to the dasboard.  If javascript is used, CGI::Ajax pushes content to the appropriate container (I use div often) when the link is clicked. 

It is all combined together on line 151 using CGI::Ajax.

I know it is a little more complicated than it probably needs to be, which is why I'm still open to looking at other more modern frameworks.

**Comment by Roflicide** [comment]
Hmm.. okay, that makes a bit more sense. Looking at the code, and reading your explanation, I can start to see how you made it piece together, and it indeed it seems quite elegant and compact. I have to admit though, I'm having some trouble wrapping my head around the program in it's entirety (which is due to my inexperience, not your coding) so if we do go with it I think I would only be able to make limited/poor contributions.

If I were to create a php script wrapped with html/css, would you be open to reviewing it? If it doesn't come out good, we can always default back to what you created. I just would like to help you out with the GUI, and php is less foreign to me, so I would be able to contribute more.

**Comment by zanix** [comment]
I think it would be good to see other ideas on a GUI, I would be up for looking at it (I'm more familiar with php than bash or perl).

**Comment by sandain** [comment]
I'm not a fan of php, if you want to go that route I'll probably not help with coding.  I could still review code and work with you on changes necessary to mscs.

I think this Perl solution is pretty simple, and I'll probably keep working on it until there is something better ready.

**Comment by sandain** [comment]
If you want to work with me on this, what I really need is someone to take the raw html/css and make it better.  I can write the Perl code.

**Comment by zanix** [comment]
I think as long as we have a good base for setting and getting data then the html/css/js would be pretty simple to "make look pretty"

**Comment by sandain** [comment]
Well I'm going to go ahead and make the queryDetailedStatus data available to the gui and add a macro for each value returned.  I'll also add a new template file called `world.xhtml` that will be used to serve up the world status retrieved from the query.  Does overviewer create a thumbnail overview of a world that could be added to this page?

**Comment by zanix** [comment]
I'm not sure that it does specifically, but you could probably get the images from the highest zoom level.

**Comment by sandain** [comment]
With commit d9e25c1d326a978bbea3526fc138adf849bed0c7, the mscs script can now provide the raw query response to the gui.  I've got a few more changes to work thru on the gui, but I almost have that side ready to go as well.

**Comment by Roflicide** [comment]
> the mscs script can now provide the raw query response to the gui
nice!

Here's my go at a theme:

![img](http://i.imgur.com/RIqSkZ5.png)

again, I would change around many many parts of the layout but I couldn't really figure out how. I think we should use a framework like bootstrap to make this so much easier--and cleaner. With the current code, however, I don't think it's viable to use something like bootstrap

**Comment by sandain** [comment]
Layout is all done via css.  What are you having issues with?

I don't know anything about bootstrap besides that it looks to be a css and js file that you load in to start using.  That could probably be done with the current setup.

**Comment by sandain** [comment]
So far, I've tested my theme on my tablet and my desktop, and it looks great.  I'll make sure it works on my phone too when I get the chance.

**Comment by Roflicide** [comment]
I'm looking forward to seeing the final product!

In terms of bootstrap, yes you are correct its essentially JavaScript and
CSS.

From how I understand the mscgui script is written, it looks for a bunch of
elements by their names and then loads them in programmatically.

So if I have a html page that organizes the CSS, I'm not sure how I can
port that over into the script since it doesn't look for an HTML page for
the layout (from my understanding). Im under the impression that the only
way to do that would be to programmatically put in like 50 tags for the 50
containers I have, which doesn't really make sense to me

**Comment by sandain** [comment]
Well it looks for macros in the xhtml files and replaces the macro with the generated content.  The normal index.xhtml file is broken out into 3 files (header.xhtml, body.xhtml, and footer.xhtml) for some valid reason I had when I first wrote this.  This could be all one file if we want.

However, to get at your question:  The header.xhtml file can be modified with <style> or <script> tags where you can add in your custom code.

**Comment by sandain** [comment]
Ohh, and if the issue is html vs xhtml, they are essentially the same thing with slightly stricter rules for xhtml.  The gui program should pass all validation tests provided by w3c as it currently stands.

I'm tempted to update the DOCTYPE to html5, but I think we should keep using the xhtml variant of the spec.

**Comment by zanix** [comment]
I think the bootstrap framework relies on the doctype being html5 so it renders correctly since some browsers enable older css adjustments if the doctype is not html5. If I have some time tomorrow I can try to get started on importing the css and js of bootstrap and may be start converting the xhtml to html5.

**Comment by zanix** [comment]
Also, do you think we should move this issue over the GUI repository?

**Comment by sandain** [comment]
I think the only thing that needs to happen is change the DOCTYPE, the rest of the code is probably compliant with html5.  We should run some tests using the w3c validation though.

**Comment by zanix** [comment]
That should hbe correct, you can use xhtml compliant code in html5 with no issues.

**Comment by sandain** [comment]
Yes.  Let's close this topic and start new ones over there.
