### ISSUE TITLE
How can update my mc server to 1.9 ? 

### ISSUE THREAD

**Issue by BogusCurry** [MinecraftServerControl/mscs#121]
Hello ;D
Maybe, I know is a stupid question, but how I can over your script update to the new version 1.9. 

But I will here say, the script is the best tool ever for a mc server .. thanks for this ;D
Greetings
Bogus | Have a nice day ;D

**Comment by sandain** [comment]
I just updated my servers.  The MSCS update command is still functioning:
```
mscs update
```
```
$ mscs status
Minecraft Server Status:
  alpha: running version 1.9 (0 of 20 users online).
```

**Comment by BogusCurry** [comment]
Ahh ok .. yes I follow the steps from the release from spigot ;D So I now the 1.9 is release, but I am very surprise. The Team are very fast to make the 1.9 rel. ;D

OK, thanks for you support ;D
