### ISSUE TITLE
Closing console continues output

### ISSUE THREAD

**Issue by ZeekDaGeek** [MinecraftServerControl/mscs#125]
Using the mscs console <world> command will allow you to view the console, however, if you use Ctrl+D to detach the output process continues to run and you will keep getting console output to your screen. The only way I've found to fix it is to go and kill the process manually.

**Comment by sandain** [comment]
I rarely use this feature so I hadn't noticed the bug, I'm sure it worked at some time in the past.  I'll give a closer look at this when I have the moment.

**Comment by Rowantrek** [comment]
I'm having the same issue? Does MSCS use Screens?

**Comment by zanix** [comment]
I too have this issue.

> I'm having the same issue? Does MSCS use Screens?

MSCS does not use screen

**Comment by sandain** [comment]
My Minecraft client does not want to work for me today, I don't know what the deal is.  Could someone test this patch for me to see if it fixes the problem?

```
diff --git a/msctl b/msctl
index d101c92..2fdc63a 100755
--- a/msctl
+++ b/msctl
@@ -1145,7 +1145,7 @@ serverConsole() {
   # Make sure that the world's directory exists.
   WORLD_DIR="$WORLDS_LOCATION/$1"
   # Follow the console output buffer file.
-  sh -c "tail --pid=\$$ -f '$WORLD_DIR/console.out'" &
+  tail -f --pid=$$ $WORLD_DIR/console.out &
   # Copy user input to the console input buffer file.
   while read LINE; do
     echo "$LINE" >> $WORLD_DIR/console.in
@@ -1209,9 +1209,9 @@ start() {
     exit 1
   fi
   # Start the server.
-  sh -c "tail -f --pid=\$$ '$WORLD_DIR/console.in' | {
-    $SERVER_COMMAND mscs-world='$1' > '$WORLD_DIR/console.out' 2>&1; kill \$$;
-    }" &
+  tail -f --pid=$$ $WORLD_DIR/console.in | {
+    $SERVER_COMMAND mscs-world=$1 > $WORLD_DIR/console.out 2>&1; kill $$;
+  } &
   # Verify the server is running.
   if [ $? -ne 0 ]; then
     printf "Error starting the server.\n"
```

**Comment by sandain** [comment]
I think the issue is that in both cases fixed here, tail was receiving the pid of `sh -c` rather than the pid of the script and so was missing the _shutdown_ signal.  I tested this as best as I could, but without a working client I'm not a 100% sure.

**Comment by sandain** [comment]
Actually, now that I think about it, we might not want the second hunk, `sh` might be necessary.  The first hunk alone should solve the problem:

```
-  sh -c "tail --pid=\$$ -f '$WORLD_DIR/console.out'" &
+  tail -f --pid=$$ $WORLD_DIR/console.out &
```

I think this should work to, but leaves `sh` in:
```
-  sh -c "tail --pid=\$$ -f '$WORLD_DIR/console.out'" &
+  sh -c "tail -f --pid=$$ $WORLD_DIR/console.out" &
```

**Comment by sandain** [comment]
> Does MSCS use Screens?

We use a couple of buffer files for the console and a couple more for Query.  An early version of this script used Screen, but I realized that the same method I was using to track the log file could be adapted to the incoming half of Query and shortly after for the console.  Output from the Minecraft server console is piped to the `console.out` file, which can then be piped to the user if requested.  Anything written to the `console.in` file is piped to the Minecraft server console.  The scripts `console` command uses the same  method, piping anything the user types to the `console.in` file while listening for changes to the `console.out` file.  Dropping Screen actually simplified the code.

**Comment by sandain** [comment]
I figured out a way to test this.  Commit 89e3d5b4e580376f6f9bf53aee69d7599f5479bf fixes this issue.  Closed.
