### ISSUE TITLE
Changing MSCS_HOME in Makefile

### ISSUE THREAD

**Issue by ZeekDaGeek** [MinecraftServerControl/mscs#126]
From what I understand configuring your install through the Makefile should allow you to change certain things the way you desire, however, when I changed MSCS_HOME in the Makefile the mscs command continued to point at /opt/mscs. I had to manually change the "mscs" file. The problem seems to be with the following:

```
# Setup the default installation location.
LOCATION=${LOCATION:-"/opt/mscs"}
```

LOCATION should be set somewhere by the Makefile should it not?

**Comment by sandain** [comment]
Instead of modifying one of the scripts, check out the [README](https://github.com/MinecraftServerControl/mscs#adjusting-global-server-settings-optional) regarding the `/etc/defaults/mscs` file.  Any values found in that file will override the default values found in the script.
