### ISSUE TITLE
Error with max memory

### ISSUE THREAD

**Issue by JulianKahnert** [MinecraftServerControl/mscs#128]
I have added this line to `/etc/default/mscs`:
`mscs-maximum-memory=2048M`

And if I try to start the server, the following error occurs:
```
/usr/local/bin/mscs: 6: /etc/default/mscs: mscs-maximum-memory=2048M: not found
/usr/local/bin/msctl: 6: /etc/default/mscs: mscs-maximum-memory=2048M: not found
/usr/local/bin/msctl: 6: /etc/default/mscs: mscs-maximum-memory=2048M: not found
```

Can you help me with this?

**Comment by zanix** [comment]
When you edit that file, the settings need to be entered as shown on this page.
https://github.com/MinecraftServerControl/mscs/wiki/Global-Server-Settings

**Comment by JulianKahnert** [comment]
Ok, thanks for your help!
