### ISSUE TITLE
Security vulnerability: privilege escalation

### ISSUE THREAD

**Issue by DanielBaulig** [MinecraftServerControl/mscs#129]
It's possible to hijack the msctl scripts user privileges and run arbitrary commands as the user msctl is running as. E.g.

    echo 'echo I can run whatever I want as `whoami`' >malicious.mscs.conf
    mscs -c malicious.mscs.conf list 

I don't think this is intentional and should probably be addressed.
But worse, with e.g. a weakly configured sudoers rule (e.g. allowing `sudo msctl` to any user), this can be even used to run arbitrary commands as an arbitrary user:

    USER_NAME=root -c malicious.mscs.conf mscs list

I think the following two steps should fix this. That said, I'm by no means a shell security expert.
1) Do not allow injection of `$USER_NAME` from the environment. Always set a default value for the case `$MSCS_DEFAULTS` does not exist
2) Do not source the configuration file. Use `IFS="=" read -r` or another approach that does not execute the content of the config file.

**Comment by zanix** [comment]
Good catch. I don't think we have had anyone check for the security of this script.

We are already parsing values in `ini` format when we read in `mscs.properties` for each world. Maybe we could go that route instead of sourcing the configuration file.

**Comment by sandain** [comment]
This is the reason I was worried about sourcing an outside file to begin with.  I agree, the best solution going forward is probably to get rid of the defaults file and move to using the code that reads in the `mscs.properties` file.  Unfortunately I have neither the time nor the will to tackle such a change at this time.  For now I will recommend only using this script in controlled environments where users can be trusted to not do such hijinks.

**Comment by zanix** [comment]
Of course if someone were to make a pull request with the changes, I'm sure it would be accepted or worked on to make it acceptable.

**Comment by sandain** [comment]
I will take the time to review pull requests.  I just don't have the time to make the required change to the code and test it to verify that the changes work.

If someone submits what looks like a reasonable fix that utilizes the parsing functions already in place and tells me that it has been tested and functions, I'll probably just accept it outright.

**Comment by sandain** [comment]
Note that a reasonable fix must include updates to the README file, particularly the `Adjusting global server settings (optional)` and `Configuring MSCS for multiple users (optional)` sections.

**Comment by sandain** [comment]
I said I wouldn't work on this, but I did anyway.  Checkout the branch I just created for this patch: cd48b2de1f2a8792fec6520fbc0cf3106b4503b4.  The wiki page will still need to be updated for the new format if everything looks good.  I've done some basic tests of this code, but I would appreciate a second or third set of eyes on this.

**Comment by sandain** [comment]
The README file on that [branch](/MinecraftServerControl/mscs/tree/mscs.defaults) has now been updated.  I'm going to stop working on this for now.  If anyone has the opportunity to give this a test I'd be happy to hear how it goes.

I did not make any changes to stop the injection of USER_NAME to the `mscs` script.  That is a simple one line change if it still needs to be done.

**Comment by zanix** [comment]
I only took a quick look, but it seems good so far. Hopefully I can find some time to test it myself.

**Comment by sandain** [comment]
I'll squash this into a couple of patches, some of the changes can go directly to master.  That should make the change log easier to follow.

**Comment by zanix** [comment]
Good idea, will be easier to follow.
Do you think a settings converter will be needed?

**Comment by sandain** [comment]
I was going to take a closer look at the perl code.. it should be able to ignore lines containing comments and remove quotes around strings.  With those abilities, the format of the file will be almost the same, just missing `mscs-` in front of the variable names.  We could add a simple converter to the Makefile maybe.

**Comment by sandain** [comment]
I stripped out the old converter code when I began

**Comment by zanix** [comment]
I would leave it as a separate file.

**Comment by sandain** [comment]
Ok, I published a new [branch](/MinecraftServerControl/mscs/compare/mscs.defaults.v2) with one commit per file.  Some of the minor changes that were in the old branch are now on master.

**Comment by zanix** [comment]
Nice, only 3 commits to look at. Makes it a bit easier to go over.

**Comment by zanix** [comment]
I made some comments directly in one of the commits.

**Comment by sandain** [comment]
I responded in that same commit.  I'll get a v3 out sometime later today to address the issues that have been brought up so far.  

What do you think of the changes so far?  Are the variable and file name changes reasonable?  The perl code is probably case insensitive, or could be set to be.  Variables now use `-`  instead of `_`, and have `mscs-` tacked on the front, but we don't have to do that.  I made the change so that it would be more uniform with the other settings files.

**Comment by zanix** [comment]
I like that there is consistency in the settings/properties files, keeping them pre-fixed  with `mscs-` is good and makes it obvious to the user they are editing MSCS settings.

I also made another comment about importing the settings files on the commit.
https://github.com/MinecraftServerControl/mscs/commit/ed876b64d1b18dc9c27a769ed676e5183bfbeb99#commitcomment-17670758

I wonder if a PR would have been better since it's easier to track comments on them.

**Comment by sandain** [comment]
Ok, v3 is now available with a [pull request](/MinecraftServerControl/mscs/pull/133).

**Comment by sandain** [comment]
What should we do about the user name override in the mscs script.  I'm fine with dropping it.  Is there a use case that requires it?

**Comment by zanix** [comment]
Since the executable defaults files are gone, I don't see how or where `USER_NAME` can be overridden.
Are you saying that `USER_NAME=${USER_NAME:-minecraft}` should be changed to `USER_NAME=minecraft` and similar for `LOCATION`?

**Comment by sandain** [comment]
yes, exactly

**Comment by zanix** [comment]
I don't see why not. `LOCATION` can still be overridden with `mscs.defaults` and the `mscs` file only exists for compatibility. The only thing I can think of is when a user wants to use the `mscs` script and change the username, but they should be able to copy or alter it.

**Comment by sandain** [comment]
I added commit ccf480bfc8c755a4f8fcb9f1961461a409845acd to the [pull request](/MinecraftServerControl/mscs/pull/133) to stop `USER_NAME` and `LOCATION` from being overridden.

**Comment by sandain** [comment]
I think things are looking pretty good.  As far as I can tell, the only thing to do is worry about whether or not we want to build in update function for this change into the Makefile, add an external script for the update function (perhaps in a subdirectory), or add some documentation so that people know about the change and can do the update themselves.

**Comment by zanix** [comment]
I would say both, but I'm not sure how hard it would be to convert the existing executable config files to the new format. Was there any other executable config file other than `/etc/default/mscs`?

**Comment by zanix** [comment]
I see that the `mscs.conf` got renamed to `mscs.defaults` for user's home directories, we probably want to add a `mv` for those.

**Comment by sandain** [comment]
Pull request #134 should finally cover this issue.  Let me know if you have the chance to give it a try.  If there are no objections, I'll merge #134 some time next week.

**Comment by sandain** [comment]
I went ahead and merged the v5 patch set with commit 0cefa4d601bc582e73d2a6319033d74890a7284a.  Closing this issue before it becomes 2 months old.

**Comment by sandain** [comment]
Thanks for updating the wiki pages @zanix

**Comment by zanix** [comment]
You are welcome
