### ISSUE TITLE
Use flock

### ISSUE THREAD

**Issue by sandain** [MinecraftServerControl/mscs#138]
Long running processes like mapping and backup could benefit from using `flock`.  The original suggestion by @Roflicide in pull request #123 was just an update to the `README` file, but I feel that it might be better to just have the `msctl` script call `flock` where needed.

I'm going to close pull request #123, any further discussion on the subject can take place in this issue instead.  I think this would be a fairly straight forward patch if anyone out there is interested in submitting something.  I may get to it eventually if I can find the time.

**Comment by zanix** [comment]
I'm slightly worried about adding another dependency that might not exist on systems other than Ubuntu since we have seen this script being used on other linux based systems.

**Comment by sandain** [comment]
I don't see why we couldn't just implement our own function that does the same thing.  You posted example code in #123 that if modified to fit the conditions of the script (ie, the pid is retrieved via a function rather than $$) could avoid the added dependency on `flock`.

**Comment by sandain** [comment]
I don't know the license on the code you mentioned, it probably isn't important, but here is a copy pasted version that might work for us:

```
createLockFile() {
  local PIDFILE
  PIDFILE=/path/to/mscs.pid
  if [ -f $PIDFILE ]; then
    ps -p $2 > /dev/null 2>&1
    if [ $? -eq 0 ];  then
      echo "Process already running"
      exit 1
    else
      ## Process not found assume not running
      echo $2 > $PIDFILE
      if [ $? -ne 0 ]; then
        echo "Could not create PID file"
        exit 1
      fi
    fi
  else
    echo $2 > $PIDFILE
    if [ $? -ne 0 ];  then
      echo "Could not create PID file"
      exit 1
    fi
  fi
}

removeLockFile() {
  local PIDFILE
  PIDFILE=/path/to/mscs.pid
  rm -f $PIDFILE
}

if $(createLockFile $1 $$); then
  $OVERVIEWER_BIN --config=$SETTINGS_FILE >> $LOG_FILE 2>&1
  $OVERVIEWER_BIN --config=$SETTINGS_FILE --genpoi >> $LOG_FILE 2>&1
  removeLockFile $1
  # Announce the location to access the world map to players.
 # ...
fi
```

**Comment by sandain** [comment]
I should mention that the above code is untested.

Also, those error messages could probably be better -- maybe include the lock type and world name.

**Comment by zanix** [comment]
I agree that using our own implementation that does the same thing is better. I'll take a look at where I got that code from.

**Comment by sandain** [comment]
This code will fail if the PIDFILE exists, but the PID that it contains belongs to a different process.  I'm not sure if it is worth capturing that problem or not -- maybe we could compare the value of `$0` with the name of the command from something like `ps -p $PID -o command --no-headers`.

**Comment by sandain** [comment]
I just created a new pull request for the code in question:  #139.  It has now been tested and seems to function for both mapping and backup.  If there are other jobs that could use this treatment, it should be easy to add them.

**Comment by sandain** [comment]
I might want to switch from variables named `pidfile` to `lockfile` for unity sake.

**Comment by zanix** [comment]
Makes sense

**Comment by zanix** [comment]
I didn't see any indication of a license on the website where I found the code. We could contact the author and ask I suppose.

**Comment by sandain** [comment]
I sent an email

**Comment by sandain** [comment]
[Benjamin Cane](http://bencane.com/) replied to my email.  We have permission to use the code:

```
Hey Jason,

It's all good. Go ahead and use the code I don't mind. I'm glad you were able to get something out of it.

On Thu, Jul 28, 2016 at 12:40 PM, Jason Wood <sandain@hotmail.com> wrote:

    Hello,

    I maintain an open source Minecraft server management shell script [1],
    and one of the features my users have requested is the ability to
    prevent duplicate cron job execution for some of the longer running
    processes.  One of my users pointed out your blog and the forever.sh
    example contained within.  A lightly modified version of this code [2]
    does exactly what we need, but there was no license for the code
    mentioned in your blog post.  While it is simple code that I could have
    written myself after some trial and error and could probably reimplement
    if necessary, I feel it would be best to get your permission to include
    your code within our 2-clause BSD project.

    The pull request that I have submitted [2] is on hold until I hear back
    from you.  I gave you credit in the pull request, but I would be happy
    to add a comment directly to the code to give you credit if you would
    prefer.  If you would rather us not use your code in this manner, I'm
    sure I can come up with something else.

    Thank you,

    Jason Wood

    [1] https://github.com/MinecraftServerControl/mscs
    [2] https://github.com/MinecraftServerControl/mscs/pull/139
```

**Comment by zanix** [comment]
Nice

**Comment by sandain** [comment]
I just committed my v2 patchset with 86e63f7107c39516801e71a37168dc611e464781. Closing this issue.
