### ISSUE TITLE
Explain that backup crontab needs to run as root

### ISSUE THREAD

**Issue by fschaap** [MinecraftServerControl/mscs#141]
Obvious in hindsight, but I spent quite a bit of time figuring out why my backups were not running. A small change to the readme telling the user to 'sudo crontab -e' will hopefully save other user a bit of time. Thanks!

**Comment by zanix** [comment]
Nice catch.
Ideally you would want to add the backup to cron with the minecraft user.
`sudo crontab -e -u minecraft`

**Comment by fschaap** [comment]
Yes, that's even better! I have changed it, thanks! I also realized later that it's about all cron jobs, not just the backups :-)

**Comment by fschaap** [comment]
Here's the thing though... I have add the backup line to the crontab of the minecraft user, but it is not executing. As root it does, but not as the minecraft user. I have looked at how the user is created, but everything appears normal. Any ideas?

I'm using Ubuntu server 16.06.1.

**Comment by Roflicide** [comment]
Hi,

Try running the commands:

chmod -R u+w /opt/mscs
chown -R minecraft:minecraft /opt/mscs

**Comment by fschaap** [comment]
Everything in /opt/mscs already has the correct permissions and was owned by the minecraft:minecraft user.

mscs and msctl in /usr/bin/local/ are both owned by root. I'll chown those to the minecraft user and see what happens.

**Comment by zanix** [comment]
`mscs` and `msctl` are ok as root
Just amke sure that your backup folder is readable, writable, and owned by the minecraft user

**Comment by fschaap** [comment]
Well, I can't get crontab to work for the minecraft user.

I have followed @Roflicide's instructions to chmod and chown. I even chowned mscs and msctl to the minecraft user. I've tested cron for the minecraft user by writing to a log file and it's running.

It's just not running the backup line that is identical with the line for root but one hour earlier.

It's not a big issue for me. I can run backups as root and it works. I'm just stumped... it _should_ work as the minecraft user.

Any ideas? Something I can try?

**Comment by conrad784** [comment]
My backup only works when I add the absolute path.:
`*/60 * *   *   *   /usr/local/bin/mscs backup`
and I changed the path to msctl in the mscs script also to the absolute location.
`# Run the msctl script.
if [ "$USER_NAME" = "$(whoami)" ]; then
    /usr/local/bin/msctl $MSCS_ARGS
else
  sudo -u $USER_NAME /usr/local/bin/msctl $MSCS_ARGS
`
Although the minecraft user was able to find these scripts in his PATH, the crontab had some problems, maybe it's worth a try for you.

**Comment by zanix** [comment]
This is a good catch. Thanks!

**Comment by sandain** [comment]
I updated the README to match the method put forth by @zanix.  I tested to make sure the method works -- I have backups happening every 10 minutes right now.  Closing this issue as done.  Thanks for finding the fix.

**Comment by fschaap** [comment]
Thanks @conrad784 and @zanix for the fix. It works as expected here was well. #happycamper
