### ISSUE TITLE
Where I must install the mods ?

### ISSUE THREAD

**Issue by BogusCurry** [MinecraftServerControl/mscs#144]
Hello ;D
Maybe is my question a little bit stupid ;D But where I must installed the mods ?

I have make a folder with name mods in the folder under /mscs/myworldname, but after restart comes nothing.
Sorry for this stupid question ;D

Have a nice Day ;D
Bogus

**Comment by sandain** [comment]
I thought that we had documentation on how to do this, but I can't find it in the README or the wiki.  I only run vanilla servers myself, so I'm not 100% here..  I think they go in a `plugins` folder in your world directory, so for a world named `alpha` installed in the usual place, you would add your plugins to `/opt/mscs/worlds/alpha/plugins`.

If you are running multiple worlds and you want all of the worlds to use the same plugins, I think you can create symbolic links, e.g:
```
mkdir /opt/mscs/plugins
ln -s /opt/mscs/plugins /opt/mscs/worlds/alpha/plugins
ln -s /opt/mscs/plugins /opt/mscs/worlds/beta/plugins
```

Maybe @zanix will chime in with more info.

We should definitely figure this out and get some documentation added.  @BogusCurry, if you give this a try, let me know how it works.

**Comment by zanix** [comment]
Here is the guide on getting alternative servers working with this script
https://github.com/MinecraftServerControl/mscs/wiki/Server-Customization-Examples

**Comment by BogusCurry** [comment]
Ok, thanks, I will test it ;D

**Comment by zanix** [comment]
I'm assuming that @BogusCurry solved their issue, closing.

**Comment by sandain** [comment]
I think we should add documentation to the [wiki](https://github.com/MinecraftServerControl/mscs/wiki/Server-Customization-Examples) before we close this issue, I am going to reopen this.

**Comment by Roflicide** [comment]
I can confirm that the documentation @zanix provided is working--I've tested it on my own enviroment. @BogusCurry You simply drag plugins into the `mods` folder like you would on any forge server. I've updated the wiki a bit to clarify this under both the spigot and forge entries but it's pretty straightforward if you've worked with Spigot/forge/bukkit before.

**Comment by sandain** [comment]
Awesome. Thank you @Roflicide for taking the time to test this and update the wiki.  Also, thank you for clarifying the `mods` vs `plugins` confusion -- it's just a `forge` vs `spigot` difference.  I'm going to close this issue.
