### ISSUE TITLE
Mirror/sync functionality bugs

### ISSUE THREAD

**Issue by seldonPlan** [MinecraftServerControl/mscs#146]
Hello, I spotted a few issues when I enabled mirroring for an existing world. They were found in the `msctl` script

**Issue 1:** globbing (`*`) being done within double quotes in `syncMirrorImage()` and `start()`functions
**Issue 2:** symlink created in `start()` causing existing mirrored world not to be read properly 

Please refer to #145 for the gritty details and proposed fix.

**Comment by sandain** [comment]
Nice finds, thanks for the patch!  I accepted your pull request.  Closing the issue.
