### ISSUE TITLE
Bug in start() - missing `$` in `WORLDS_LOCATION` directory check

### ISSUE THREAD

**Issue by seldonPlan** [MinecraftServerControl/mscs#147]
see https://github.com/MinecraftServerControl/mscs/blob/master/msctl#L1038

`WORLDS_LOCATION` should be `$WORLDS_LOCATION` (missing the **$** needed for variable expansion).

**Comment by sandain** [comment]
Nice find. Do you want to submit a patch?

**Comment by seldonPlan** [comment]
#148 created

thanks!

**Comment by sandain** [comment]
Patch accepted with commit 9076dddc72d4a15e8c98c961dbf71aa0b59ab39f. Thanks!
