### ISSUE TITLE
Forge install instructions minor error

### ISSUE THREAD

**Issue by EarlsvenT** [MinecraftServerControl/mscs#155]
The [instructions for installing forge]((https://github.com/MinecraftServerControl/mscs/wiki/Server-Customization-Examples#forge)) are slightly incorrect:

The example mscs.properties file given is 

```
mscs-client-version=1.8.4
mscs-server-version=1.8.4
mscs-server-jar=forge-1.8.9-11.15.1.1722-installer.jar
mscs-server-url=
```

The third line should read something like `mscs-server-jar=forge-1.8.9-11.15.1.1722-universal.jar` rather than `installer.jar`.

The server fails to start with unknown PID if the instructions are followed exactly.

**Comment by sandain** [comment]
Nice catch!  The wiki page is editable by everyone, but I went ahead and made that fix.  Closing this issue.
