### ISSUE TITLE
Server cannot be started via SSH forcecommand

### ISSUE THREAD

**Issue by mozuzu** [MinecraftServerControl/mscs#162]
I wanted to automate server launching with SSH. However, I noticed that the server's process is automatically terminated when _mscs start_ is called from _authorized\_keys_.
So the Minecraft server didn't start.

Problem:

    $ cat /opt/mscs/.ssh/authorized_keys
      command="/usr/local/bin/mscs start myworld" ssh-ed25519 AAAAC3Nz...

    (ssh-client) $ ssh -i id_ed25519 -T minecraft@minecraft-server  # Start the server from SSH client
                   Starting Minecraft Server: myworld.

    $ mscs status myworld
      Minecraft Server Status:
        myworld: not running.  # <- The server is not running!

A workaround is to redirect _stdin_, _stdout_ and _stderr_ to _/dev/null_.
The catch is the SSH client cannot retreive any messages from MSCS:

    $ cat /opt/mscs/.ssh/authorized_keys
      command="/usr/local/bin/mscs start myworld 2> /dev/null >&2 <&2" ssh-ed25519 AAAAC3Nz...

    (ssh-client) $ ssh -i id_ed25519 -T minecraft@minecraft-server
                   (Nothing displayed cause all the outputs are redirected.)

    $ mscs status myworld
      Minecraft Server Status:
        myworld: running.
          Process ID: ...

A possible fix below would solve the problem:

    diff --git a/mscs/msctl b/usr/local/bin/msctl
    index b592192..5b51c1e 100755
    --- a/mscs/msctl
    +++ b/usr/local/bin/msctl
    @@ -1085,7 +1085,7 @@ start() {
       # Start the server.
       sh -c "tail -f --pid=\$$ $WORLD_DIR/console.in | {
         $SERVER_COMMAND mscs-world=$1 > $WORLD_DIR/console.out 2>&1; kill \$$;
    -  }" &
    +  }" 2> /dev/null >&2 <&2 &
       # Verify the server is running.
       if [ $? -ne 0 ]; then
         printf "Error starting the server.\n"

Thanks!

**Comment by sandain** [comment]
That seems like a nice fix.  My one question is what each of the redirects mean, I'm not familiar with them all.

Obviously, `2>/dev/null` is piping STDERR to `/dev/null`.

However, I'm confused with what `>&2` and `<&2` are doing.  I'd be happy to implement this patch with a little more info. Thanks!

**Comment by sandain** [comment]
Well I've given this a shot and I can't get your patch to work.

```
$ ssh -t whitney "mscs status"
[sudo] password for jwood: 
Minecraft Server Status:
  alpha: running version 1.11.2 (0 of 20 users online).
    Process ID: 2217.
    Memory used: 499656 kB.
Connection to 192.168.1.5 closed.
$ ssh -t whitney "mscs stop alpha"
[sudo] password for jwood: 
Stopping Minecraft Server: alpha.
Connection to 192.168.1.5 closed.
$ ssh -t whitney "mscs status"
[sudo] password for jwood: 
Minecraft Server Status:
  alpha: not running.
Connection to 192.168.1.5 closed.
$ ssh -t whitney "mscs start alpha"
[sudo] password for jwood: 
Starting Minecraft Server: alpha.
Connection to 192.168.1.5 closed.
```

So both the `status` and `stop` commands work as expected. However, the start command fails without any message as to why it fails.  This is the same result with or without your patch.  I'll keep digging and see if I can find a solution.

**Comment by sandain** [comment]
Good ol' `nohup` to the rescue.  The following does the trick for me:

``` diff
diff --git a/msctl b/msctl
index b592192..715ef3b 100755
--- a/msctl
+++ b/msctl
@@ -1083,9 +1083,9 @@ start() {
     exit 1
   fi
   # Start the server.
-  sh -c "tail -f --pid=\$$ $WORLD_DIR/console.in | {
-    $SERVER_COMMAND mscs-world=$1 > $WORLD_DIR/console.out 2>&1; kill \$$;
-  }" &
+  nohup sh -c "tail -f --pid=\$$ $WORLD_DIR/console.in | {
+    echo testing; $SERVER_COMMAND mscs-world=$1 > $WORLD_DIR/console.out 2>&1; kill \$$;
+  }" > /dev/null 2>&1 &
   # Verify the server is running.
   if [ $? -ne 0 ]; then
     printf "Error starting the server.\n"
```

**Comment by sandain** [comment]
It looks like the Query handler also fails to start.  That might require a second patch that does the same thing.

**Comment by sandain** [comment]
This fixes the Query handler:

```diff
diff --git a/msctl b/msctl
index b592192..f6e29fb 100755
--- a/msctl
+++ b/msctl
@@ -1083,9 +1083,9 @@ start() {
     exit 1
   fi
   # Start the server.
-  sh -c "tail -f --pid=\$$ $WORLD_DIR/console.in | {
+  nohup sh -c "tail -f --pid=\$$ $WORLD_DIR/console.in | {
     $SERVER_COMMAND mscs-world=$1 > $WORLD_DIR/console.out 2>&1; kill \$$;
-  }" &
+  }" > /dev/null 2>&1 &
   # Verify the server is running.
   if [ $? -ne 0 ]; then
     printf "Error starting the server.\n"
@@ -1099,7 +1099,7 @@ start() {
   fi
   # Start the Query handler if enabled.
   if [ "$(getServerPropertiesValue $1 'enable-query')" = "true" ]; then
-    queryStart "$1" &
+    nohup queryStart "$1" > /dev/null 2>&1 &
   fi
   # Create a PID file for the world server.
   echo $PID > "$WORLDS_LOCATION/$1.pid"
```

**Comment by mozuzu** [comment]
I'm sorry for the late replay.

Thank you for the follow up. I confirmed that your patch worked nicely!

----

> Does STDIN need to be redirected?

Yes, according to [this Wikipedia article](https://en.wikipedia.org/wiki/Nohup#Overcoming_hanging):

    This problem can also be overcome by redirecting all three I/O streams:
      $ nohup ./myprogram > foo.out 2> foo.err < /dev/null &

So you may want to add "<&1" or simply "< /dev/null" to your patch.

----

> Is it piping STDOUT and STDIN to STDERR? Why not use the standard > /dev/null 2>&1?

Thanks for letting me realize the very confusing syntax. I self-taught shell scripting so there may be some weirdness. All three streams are redirected to /dev/null by doing "2> /dev/null >&2 <&2". It's the same as "> /dev/null 2>&1 <&1".

----

> I'm also assuming that the redirects are only affecting the sh command and not tail or $SERVER_COMMAND...

That's exactly right.

**Comment by mozuzu** [comment]
I'd like to change the code a little bit.

Since nohup cannot be applied to a shell function, "nohup queryStart" causes an error "nohup: failed to run command ‘queryStart’". This is because nohup is an external command, not a shell's built-in command. An external command cannot recognize shell functions.

So I'd propose using _disown_ for queryStart. "sh -c ..." has no problem with  nohup although _disown_ could also be used for the purpose of consistency.

```diff
diff --git a/mscs/msctl b/usr/local/bin/msctl
index b592192..c392e5d 100755
--- a/mscs/msctl
+++ b/usr/local/bin/msctl
@@ -1083,9 +1083,9 @@ start() {
     exit 1
   fi
   # Start the server.
-  sh -c "tail -f --pid=\$$ $WORLD_DIR/console.in | {
+  nohup sh -c "tail -f --pid=\$$ $WORLD_DIR/console.in | {
     $SERVER_COMMAND mscs-world=$1 > $WORLD_DIR/console.out 2>&1; kill \$$;
-  }" &
+  }" > /dev/null 2>&1 <&1 &
   # Verify the server is running.
   if [ $? -ne 0 ]; then
     printf "Error starting the server.\n"
@@ -1099,7 +1099,8 @@ start() {
   fi
   # Start the Query handler if enabled.
   if [ "$(getServerPropertiesValue $1 'enable-query')" = "true" ]; then
-    queryStart "$1" &
+    queryStart "$1" > /dev/null 2>&1 <&1 &
+    disown -h
   fi
   # Create a PID file for the world server.
   echo $PID > "$WORLDS_LOCATION/$1.pid"
```

**Comment by mozuzu** [comment]
By the way, I apologize for my first post being unorganized.

I don't understand how the BASH and its background job's persistence work to be honest. So I'm not sure the patches above always work as intended.

I've tried several different configurations since the first post and I've got seemingly inconsistent results everytime I tried. So I decided to consult some books including _The Linux Programming Interface_ and read some relevant chapters (_"Chapter 34: Process Groups, Sessions and Job Control"_,  _"Chapter 62: Terminals"_ and _"Chapter 64: pseudoterminals"_). But they didn't help understand much.

First of all, nohup does work in msctl. But it doesn't in the following case. I don't get it:

    (SSH client) $ ssh -t user@server 'nohup tail -f /etc/fstab > /dev/null 2>&1 <&1 &'

    (SSH server) $ ps aux | grep -v grep | grep 'tail -f /etc/fstab'
                   (Nothing displayed.)  # <- No process remains!

However, when you turn the option _-t_ (lower case) to _-T_ (upper case), it works:

    (SSH client) $ ssh -T user@server 'nohup tail -f /etc/fstab > /dev/null 2>&1 <&1 &'

    (SSH server) $ ps aux | grep -v grep | grep 'tail -f /etc/fstab'
                   user    32731  0.0  0.0   5844   692 ?    S    12:37   0:00 tail -f /etc/fstab

Lastly, with _-T_ (upper case) option, _mscs start_ works perfectly without nohup as I did in the first post. I'm so confused.

**Comment by sandain** [comment]
If we can't use `nohup` on `queryStart`, I think we should just move the change into that subroutine.  The offending statement appears to be the call to `tail` in both cases.

Try this patch and let me know how it works:
```diff
diff --git a/msctl b/msctl
index b592192..4020894 100755
--- a/msctl
+++ b/msctl
@@ -1083,9 +1083,9 @@ start() {
     exit 1
   fi
   # Start the server.
-  sh -c "tail -f --pid=\$$ $WORLD_DIR/console.in | {
+  nohup sh -c "tail -f --pid=\$$ $WORLD_DIR/console.in | {
     $SERVER_COMMAND mscs-world=$1 > $WORLD_DIR/console.out 2>&1; kill \$$;
-  }" &
+  }" > /dev/null 2>&1 &
   # Verify the server is running.
   if [ $? -ne 0 ]; then
     printf "Error starting the server.\n"
@@ -1099,7 +1099,7 @@ start() {
   fi
   # Start the Query handler if enabled.
   if [ "$(getServerPropertiesValue $1 'enable-query')" = "true" ]; then
-    queryStart "$1" &
+    queryStart "$1"
   fi
   # Create a PID file for the world server.
   echo $PID > "$WORLDS_LOCATION/$1.pid"
@@ -1428,25 +1428,26 @@ overviewer() {
 # @param 1 The world server to start a Query handler for.
 # ---------------------------------------------------------------------------
 queryStart() {
-  local WORLD_DIR SERVER_IP QUERY_PORT
+  local WORLD_DIR SERVER_IP SERVER_PID QUERY_PORT
   # Grab the location of the world's directory.
   WORLD_DIR="$WORLDS_LOCATION/$1"
   # Determine the IP address and port used by the query server.
   SERVER_IP=$(getServerPropertiesValue $1 'server-ip' '127.0.0.1')
   QUERY_PORT=$(getServerPropertiesValue $1 'query.port')
+  SERVER_PID=$(getJavaPID $1)
   # Delete any old query.in or query.out buffer files.
   rm -Rf "$WORLD_DIR/query.in" "$WORLD_DIR/query.out"
-  # Give the server a moment to start before initializing the
-  # Query handler.
-  sleep 20
   # Initialize the query.in and query.out buffer files.
   printf '' > "$WORLD_DIR/query.in"
   printf '' > "$WORLD_DIR/query.out"
   # Start a tail process to watch for changes to the query.in file to pipe
   # to the Minecraft query server via socat.  The response from the query
   # server is piped into the query.out file.
-  tail -f --pid=$(getJavaPID $1) "$WORLD_DIR/query.in" | \
-    $SOCAT - UDP:$SERVER_IP:$QUERY_PORT > "$WORLD_DIR/query.out"
+  nohup sh -c "
+    sleep 20;
+    tail -f --pid=$SERVER_PID \"$WORLD_DIR/query.in\" |
+    $SOCAT - UDP:$SERVER_IP:$QUERY_PORT > \"$WORLD_DIR/query.out\"
+  " > /dev/null 2>&1 &
   # Verify the connection to the query server worked.
   if [ $? -ne 0 ]; then
     printf "Error connecting to the query server.\n"
```

**Comment by mozuzu** [comment]
Please forget about what I said regarding disown. I somehow thought this script used bash. sh can't use it.

I tested the queryStart patch. It worked except when I start the server as 'minecraft' user, which mscs uses. When I use another user, it worked just fine.

As 'minecraft' user:

    $ ssh -i minecraft_ed25519 -t minecraft@minecraft 'mscs stop'
    Stopping Minecraft Server: Fragment.
    Connection to minecraft closed.

    $ ssh -i minecraft_ed25519 -t minecraft@minecraft 'mscs start'
    Starting Minecraft Server: Fragment.
    Connection to minecraft closed.

    $ sleep 20

    $ ssh -i minecraft_ed25519 -t minecraft@minecraft 'mscs query Fragment'
    Connection to minecraft closed.

As another user:

    $ ssh -t k@minecraft 'mscs stop'
    [sudo] password for k:
    Stopping Minecraft Server: Fragment.
    Connection to minecraft closed.

    $ ssh -t k@minecraft 'mscs start'
    [sudo] password for k:
    Starting Minecraft Server: Fragment.
    Connection to minecraft closed.

    $ sleep 20

    $ ssh -t k@minecraft 'mscs query Fragment'
    [sudo] password for k:
    0       1       splitnum        128     0       hostname        A Minecraft Server      gametype        SMP     game_id MINECRAFT       version 1.9.2   plugins               map     Fragment        numplayers      0       maxplayers      20      hostport        25565   hostip  192.168.72.11   0       1       player_       0
    Connection to minecraft closed.

**Comment by sandain** [comment]
That's odd, I wonder why that would be the case.  I'm busy today and won't have the opportunity to look at this, but I'll try to do so soon.

**Comment by sandain** [comment]
I thought about this more and realized that I'm going to need to do some work to test this. I currently have the _minecraft_ user locked down on my server -- it is a system account, it doesn't have a login shell, and it has no access to `ssh`. I'll either need to modify these restrictions on my server or setup a new virtual environment without those restrictions.  Either way, I probably don't have time to work on this in the immediate future.

RE your question on the `-t` vs `-T` command line option for `ssh`: it has to do with psudo-terminal allocation. Here are the man page entries from `dash`:
```
     -T      Disable pseudo-terminal allocation.

     -t      Force pseudo-terminal allocation.  This can be used to execute
             arbitrary screen-based programs on a remote machine, which can be
             very useful, e.g. when implementing menu services.  Multiple -t
             options force tty allocation, even if ssh has no local tty.
```

I don't know what this means. Hopefully using `nohup` will work with either option.

**Comment by mozuzu** [comment]
Starting and querying the server as 'minecraft' user succeeded when I specify the _-T_ option as you implied:

    $ ssh -i minecraft_ed25519 -T minecraft@minecraft.gs 'mscs stop'
    Stopping Minecraft Server: Fragment.

    $ ssh -i minecraft_ed25519 -T minecraft@minecraft.gs 'mscs start'
    Starting Minecraft Server: Fragment.

    $ sleep 20s

    $ ssh -i minecraft_ed25519 -T minecraft@minecraft.gs 'mscs query Fragment'
    0       1       splitnum        128     0       hostname        A Minecraft Server      gametype        SMP     game_id MINECRAFT       version   1.9.2   plugins         map     Fragment        numplayers      0       maxplayers      20      hostport        25565   hostip  192.168.72.11     0       1       player_ 0

Another thing I found is that it worked flawlessly even with the _-t_ option
when I inserted 'sleep 1' in start() after queryStart() returned.

Inserted 'sleep 1' in your patch:

```diff
diff --git a/mscs/msctl b/usr/local/bin/msctl
index 4020894..d26cd26 100755
--- a/mscs/msctl
+++ b/usr/local/bin/msctl
@@ -1100,6 +1100,7 @@ start() {
   # Start the Query handler if enabled.
   if [ "$(getServerPropertiesValue $1 'enable-query')" = "true" ]; then
     queryStart "$1"
+    sleep 1
   fi
   # Create a PID file for the world server.
   echo $PID > "$WORLDS_LOCATION/$1.pid"

```

And it worked successfully with the _-t_ option:

    $ ssh -i minecraft_ed25519 -t minecraft@minecraft.gs 'mscs stop'
    Stopping Minecraft Server: Fragment.
    Connection to minecraft.gs closed.

    $ ssh -i minecraft_ed25519 -t minecraft@minecraft.gs 'mscs start'
    Starting Minecraft Server: Fragment.
    Connection to minecraft.gs closed.

    $ sleep 20

    $ ssh -i minecraft_ed25519 -t minecraft@minecraft.gs 'mscs query Fragment'
    0       1       splitnum        128     0       hostname        A Minecraft Server      gametype        SMP     game_id MINECRAFT       version   1.9.2   plugins         map     Fragment        numplayers      0       maxplayers      20      hostport        25565   hostip  192.168.72.11     0       1       player_ 0
    Connection to minecraft.gs closed.

I don't know why but one thing I can say for sure is it has always worked as intended when I use the _-T_ option.

**Comment by sandain** [comment]
That is interesting that adding `sleep 1` fixes the issue when using `-t` and that it always seems to work with the `-T` option.  I wish I better understood what those options mean.  I'll put together another patch that combines my previous version with your change and push it to master -- unless there are other issues that need to be addressed.

**Comment by mozuzu** [comment]
Thank you for taking your time to help me with the problem. I also wish I better understood what those options and such work.

**Comment by sandain** [comment]
Glad I could help @mozuzu.  Thanks for your help working this out.  I just sent in commit df29679a0c2a5a359c50d4d37f247ce65c45076c that should fix this issue. Closing.
