### ISSUE TITLE
How to unnistall ?

### ISSUE THREAD

**Issue by Cuthmf0** [MinecraftServerControl/mscs#163]
Hello, I would like to uninstall, because the folder that is the name of the world is this way servername, servername_nether, servername_end. I would like to know if it is possible to leave the default name or uninstall.

Sorry for my awful English.

**Comment by sandain** [comment]
It depends on what you want to uninstall. There is no full uninstall option, but it really wouldn't be hard to add.

If you want to stop your server from automatically starting your world servers, the Makefile has the `clean` option that can be accessed via the command `make clean`.  This will remove the script but leave everything in the `/opt/mscs/` folder, including settings and world files.  This will also leave the `minecraft` user account alone.

If you want to remove a world, the `mscs` or `msctl` scripts have the `delete` option (see the [README](https://github.com/MinecraftServerControl/mscs#command-reference)).  If your world's name is `servername` that you want to delete, you can issue the command `mscs delete servername`.

If you want to do a full uninstall, you would probably want to delete all of your worlds and run the `clean` command. To remove the rest you would want to delete the `/opt/mscs/` folder and remove the `minecraft` user. To summarize:
```
mscs delete servername
make clean
userdel -f -r minecraft
rm -Rf /opt/mscs/
```
```

**Comment by Roflicide** [comment]
@Cuthmf0 ¿Desea desinstalar MSCS? ¿O desea importar un mundo llamado "servername" en MSCS?

**Comment by sandain** [comment]
Closing this issue due to lack of response from @Cuthmf0.
