### ISSUE TITLE
somehow being able to increase the $VERSIONS_DURATION from 30 min?

### ISSUE THREAD

**Issue by erikyuzwa** [MinecraftServerControl/mscs#170]
hey all,
First of all just wanted to let this team know how much I'm appreciating this tool! It's been holding up extremely well through some of the crazy stuff I've been trying to do. :bow:

In a recent update, I've been noticing that on every `restart` the tool does some kind of check with the manifest to determine that it's older then 30min, at which point a newer version is hunted for.

Definitely should be considered a low priority / non-essential, but is there somewhere I can edit to change that 30min check? I thought it was using the `$VERSIONS_DURATION` flag, but when I modify this value it seems to have no effect.

Any ideas? Thanks a ton!

**Comment by zanix** [comment]
Look here
https://github.com/MinecraftServerControl/mscs#adjusting-global-server-properties

**Comment by erikyuzwa** [comment]
thanks @zanix - I'll check that out. 👍

**Comment by Roflicide** [comment]
Hi @erikyuzwa,

Did you figure out the issue? You have to add `mscs-versions-duration` to either your `mscs.defaults` file (this is global, server-wide properties file) or to your `mscs.properties` file (this is the per-world properties file, which exists in each world folder). By default, `mscs-versions-duration=30`, which means it checks it every 30 minutes.

**Comment by erikyuzwa** [comment]
hi @Roflicide - 
Yes I did...so sorry for taking so long to verify. I'm struggling with a race condition in one of my scripts which seems to be the root problem. But that was the exact property I need. 
Thanks again :bow:
