### ISSUE TITLE
Failed to start server

### ISSUE THREAD

**Issue by Cuthmf0** [MinecraftServerControl/mscs#171]
Hello, I'm having the following error when I start the server.

```
The cached copy of the version manifest is up to date.
Use the force-update option to ensure a new copy is downloaded.
Starting Minecraft Server: teste/usr/local/bin/msctl: line 1159: 23561 Terminated              nohup sh -c "tail -f --pid=\$$ $WORLD_DIR/console.in | {
    $SERVER_COMMAND mscs-world=$1 > $WORLD_DIR/console.out 2>&1; kill \$$;
  }" > /dev/null 2>&1
Error starting the server: couldn't retrieve the server's process ID.
root@ns3086735:~# Error starting the server: couldn't retrieve the server's process ID.
```

**Comment by sandain** [comment]
I'm not sure what the problem is, so I'll need more information from you.  Have you made any modifications to the script?  What process did you use to install the script (did you run `make` or do it manually)? What is the output of `which java`?  `which nohup`? `which tail`?

**Comment by Cuthmf0** [comment]
Hello, i solved the problem, I was running a version of Java 7
