### ISSUE TITLE
Backup error

### ISSUE THREAD

**Issue by Cuthmf0** [MinecraftServerControl/mscs#172]
Hello, Hello, I'm trying to backup, but I'm encountering errors

Erros:

`Backing up Minecraft Server: bungee lobby minigames rankupFatal Error: File /opt/mscs/worlds/rankup does not look like an increment file.

Try restoring from an increment file (the filenames look like
"foobar.2001-09-01T04:49:04-07:00.diff").
Error doing backup of world rankup
.
`

**Comment by Roflicide** [comment]
Hello, 

What does the output of `mscs status` say? Did you do anything else to the `rankup` world? I'm inclined to think that, because all of the other worlds are backing up correctly, you may have misconfigured the `rankup` world. Try re-creating it or re-importing it.

**Comment by Cuthmf0** [comment]
I remember I backed it up once, but I restored it wrongly, I copied the server that was in the backup folder, and pasted it to / opt / mscs / worlds

What do I do to fix this?

**Comment by Roflicide** [comment]
You should be able to copy the  `rankup` world folder in `/opt/mscs/worlds/rankup` (note: copy the `rankup` world folder found WITHIN the `rankup` folder). Then, follow the instructions on the readme on [how to import a world](https://github.com/MinecraftServerControl/mscs#importing-an-existing-world), using the folder you just copied.

**Comment by zanix** [comment]
You might have copied the backup metadata folder. Look for a folder named `rdiff-backup-data` in `/opt/mscs/worlds/rankup`. If it's there, delete it.

**Comment by Roflicide** [comment]
@Cuthmf0 Hi, have you fixed this?
