### ISSUE TITLE
Multiple world commands

### ISSUE THREAD

**Issue by csdt** [MinecraftServerControl/mscs#185]
Many commands can deal with multiple worlds at the same time:
```
* start [world]
* stop [world]
* force-stop [world]
* restart [world]
* force-restart [world]
* status [world]
* logrotate [world]
* backup [world]
* map [world]
* update [world]
```

But we can only either execute such a command for one single world, or all of them.
I think it would be great to be able to specify multiple worlds for those commands

**Comment by sandain** [comment]
This would be fairly easy to implement if someone is looking for a project. I would, but I don't really have the time right now.

**Comment by sandain** [comment]
@Roflicide sent in PR #205 to add this feature, so closing this issue.  Thanks @Roflicide!
