### ISSUE TITLE
mscs start bungecord breaks console

### ISSUE THREAD

**Issue by david-bla** [MinecraftServerControl/mscs#186]
Hey, first I'd like to thank you for MSCS 👍 

I'm on the way switching from spigot single servers to bungecord.
There is one very annoying... every time I type mscs start <bungecordinstance> my console breaks.
I cannot read the chars I'm typing (like typing password) and CR is not working so a hit on "return" will not open a new line. 
But if i type a command right the server gets it and runs it like normal...
I tried 3 ssh clients, its the same in everyone.

Btw. sometimes mscs stop <bungeecordinstance> is not working to i had to kill <pid>

Best Regards and Thank you in advance

**Comment by sandain** [comment]
I just ssh'd into my server running three worlds plus bungeecord on Ubuntu 18.04 and could not confirm this issue. I tried from two different computers (1 running Windows 10 with WSL, the other Ubuntu 18.04).  I'll try again in a few hours when I have physical access to the server.

I remember seeing behavior like this before, but I thought we fixed it about a year ago with commit df29679a0c2a5a359c50d4d37f247ce65c45076c.  Are you running the most up-to-date version of MSCS?

If the `stop` command is not working for some reason, try the `force-stop` command instead of manually killing the process.

**Comment by sandain** [comment]
I tried again from a local console on my server and could not reproduce this issue. Could you provide a little more information about the environment with this issue?  What distro and version are you running your server on?

**Comment by david-bla** [comment]
Hey, thank you for caring and fast reply 👍
<details><summary>mscs stop and start</summary>
<pre><code>
minecraft@<my_server>:~$
minecraft@<my_server>:~$
minecraft@<my_server>:~$
minecraft@<my_server>:~$ mscs stop bungee
Stopping Minecraft Server: bungee.
minecraft@<my_server>:~$
minecraft@<my_server>:~$
minecraft@<my_server>:~$
minecraft@<my_server>:~$ mscs start bungee
The cached copy of the version manifest is up to date.
Use the force-update option to ensure a new copy is downloaded.
Starting Minecraft Server: bungee.
minecraft@<my_server>:~$ minecraft@<my_server>:~$ minecraft@<my_server>:~$ minecraft@<my_server>:~$ minecraft@<my_server>:~$ minecraft@<my_server>:~$ minecraft@<my_server>:~$ minecraft@<my_server>:~$ minecraft@<my_server>:~$ minecraft@<my_server>:~$ minecraft@<my_server>:~$ minecraft@<my_server>:~$ minecraft@<my_server>:~$ minecraft@<my_server>:~$ minecraft@<my_server>:~$
</code></pre>
</details>

After the Starting lines (as i mentioned in first post) all keyboard inputs are hidden, but everything is working.
This means new lines on return or every other commands becomes executed and the console is printing the output normaly.

__And this is only related to this one bungeecord "world" - this is never happening if i start/stop my spigot servers.__

There was a crazy behavior today, I was on the way to copy these above lines...
but it was 6am and i failed to `su minecraft` (my user how runs minecraft server) and executed `mscs stop bungee` `mscs start bungee` and the issue was gone.

But I was not able to reproduce it, I lanched the commands a second time and the behavior was like I mentioned.
<details><summary>mscs stop and start with root</summary>
<pre><code>
root@<my_server>:/opt/mscs#
root@<my_server>:/opt/mscs#
root@<my_server>:/opt/mscs#
root@<my_server>:/opt/mscs# mscs stop bungee
Stopping Minecraft Server: bungee
root@<my_server>:/opt/mscs#
root@<my_server>:/opt/mscs#
root@<my_server>:/opt/mscs#
root@<my_server>:/opt/mscs#
root@<my_server>:/opt/mscs# mscs start bungee
The cached copy of the version manifest is up to date.
Use the force-update option to ensure a new copy is downloaded.
Starting Minecraft Server: bungee.
root@<my_server>:/opt/mscs# root@<my_server>:/opt/mscs# root@<my_server>:/opt/mscs# root@<my_server>:/opt/mscs# root@<my_server>:/opt/mscs# root@<my_server>:/opt/mscs# root@<my_server>:/opt/mscs# root@<my_server>:/opt/mscs#
</code></pre>
</details>

Some details about my enviroment:
- It's a VM the Hypervisor is a Virtuozzo System
- Ubuntu 16.04.4 LTS (4.4.0-042stab128.2)
- 6x Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz 
- 12GB RAM 
- SSD NAS 

I've create a user e.g. `minecraft` for dealing with mscs.

```
root@<my_server>:~/mscs# git pull
Already up-to-date.
```

Is there a way to query mscs for its version? maybe the `make update` process fails.
_(Would be great to provide a clear output e.g. __Successfully  updated MSCS__ )_

**Comment by sandain** [comment]
I'll create an Ubuntu 16.04 virtual box and see if I can replicate the issue.

I never created a version field in the script. If you ran git pull and installed it, you should be running the most recent version.

**Comment by david-bla** [comment]
Yes, I think so.
I tried `make update` and /usr/loca/bin/mscs became updated (timestmap)

btw: if i ran `make update` i get
```
install -m 0755 msctl /usr/local/bin/msctl
install -m 0755 mscs /usr/local/bin/mscs
install -m 0644 mscs.completion /etc/bash_completion.d/mscs
if which systemctl; then \
        install -m 0644 mscs.service /etc/systemd/system/mscs.service; \
fi
/bin/systemctl
```

Thank you for your investigations, I'll set up a clean enviroment too, if I got some free time... - I think we're all facing the same time issue, specially for developing free software without monitorization

**Comment by sandain** [comment]
I created a Ubuntu 16.04 VM, and I can confirm that BungeeCord causes the issue described here.  I don't know what a fix will be at this time, but I can at least reproduce it.

**Comment by sandain** [comment]
I found a solution. Please try the following patch on `msctl`:

```patch
diff --git a/msctl b/msctl
index 5c036eb..d4bae37 100755
--- a/msctl
+++ b/msctl
@@ -1235,6 +1235,9 @@ start() {
     printf "Error starting the server.\n"
     exit 1
   fi
+  # Reset the terminal to fix an issue with echo with some server software.
+  tset
+  # Retrieve the process ID for the server.
   sleep 1
   PID=$(getJavaPID "$1")
   if [ $PID -eq 0 ]; then

```

**Comment by david-bla** [comment]
yes, i can confirm that resetting the console with `tset` is working.
using `tset` after these lines
https://github.com/MinecraftServerControl/mscs/blob/c0d8ecd113886fcf08bd9accadf1585cc70c992c/msctl#L1230-L1232
will fix the issue.

I can confirm that `stty echo` does also the trick.
`stty -echo` produces this behavior and `stty echo` will enable echoing of characters again.
But I'm not sure about the root cause.

**Comment by sandain** [comment]
I just submitted commit 9235f35462aee5126c20b17f6dc37da44f29eaef to fix this issue.  I used `stty echo` rather than `tset` because it makes fewer changes to the terminal config but still fixes the issue.
