### ISSUE TITLE
tset: terminal attributes: No such device or address

### ISSUE THREAD

**Issue by PhasecoreX** [MinecraftServerControl/mscs#193]
I have a cron job that runs as the minecraft user and restarts my server daily (after my own updating plugins script). Before updating recently, this cron worked just fine:

```
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
00 05 * * *   minecraft   python3.5 update.py && mscs restart
```

However now, whenever `mscs restart` is called via cron, I get this error in my cron logs:

`tset: terminal attributes: No such device or address`

It looks like a couple months ago things were being done with `tset` and `stty echo`, in issue #186. Perhaps that's the cause of my cron problems.

**Comment by sandain** [comment]
Are your servers restarting as expected and you are just receiving this error message?

After doing some research, I think changing the line that calls `tset` to `tty -s && tset` might do the trick.  Basicially, if there is no tty, `tset` will not be called with this change.  I'll have to verify that this change won't reintroduce the issue #186 if it works for you.

**Comment by PhasecoreX** [comment]
I actually didn't realize it, but checking the logs, it was restarting the server successfully. I just figured the Segmentation Fault message it spits out after wasn't good, so I would restart it manually when I woke up.

I replaced `tset` with `tty -s && tset` in the code and modified my cron to run it, and it fixed the error! Thank you!

**Comment by sandain** [comment]
Sweet. I'll see if I can replicate the issue identified in #186 again and see if this change still fixes the problem. If it does, I'll commit the change.

Thanks for the bug report and testing the fix!

**Comment by sandain** [comment]
I can't replicate issue #186 anymore. I'm just going to commit this change and hope for no fallout.

**Comment by sandain** [comment]
I just sent in commit cd0f9c2ad68540096a63662b8f6e83281d285720 to fix this
