### ISSUE TITLE
Error updating the Minecraft server software.

### ISSUE THREAD

**Issue by IamSAB** [MinecraftServerControl/mscs#198]
Trying to create a new world of current minecraft version. Always get this error

```
The cached copy of the version manifest is up to date.
Use the force-update option to ensure a new copy is downloaded.
Starting Minecraft Server: alphaError updating the Minecraft server software.
```
did force-update and also ping mojang.com which works. the 1.13.1 jar is also in the server folder

OS
Ubuntu 16.04

MSCS
up to date, did git pull & mscs make update

JAVA
```
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

**Comment by IamSAB** [comment]
This error only occurs for MC versions > 1.12.2, currently for versions 1.13 -1.13.1

**Comment by sandain** [comment]
Odd. Please try running:
```
  perl -0777ne '
    use JSON;
    use LWP::Simple;
    my $json = decode_json ($_);
    my $version;
    foreach $ver (@{$json->{versions}}) {
      $version = $ver if ($ver->{id} eq "1.13.1");
    }
    $json = decode_json (get ($version->{url}));
    print $json->{downloads}{server}{url};
  ' /opt/mscs/version_manifest.json
```
This should print out a valid URL for the 1.13.1 server.jar file.

**Comment by sandain** [comment]
Also, please post a copy of the `mscs.defaults` file and the `mscs.properties` file for the new world.  You can also check that your minecraft user has `rw` access to the `\opt\mscs\server` folder.

**Comment by IamSAB** [comment]
The output from your cli code:
``
https://launcher.mojang.com/v1/objects/fe123682e9cb30031eae351764f653500b7396c9/server.jar
``

**Comment by IamSAB** [comment]
mscs.defaults
``
mscs-location=/opt/mscs
mscs-worlds-location=/opt/mscs/worlds
mscs-versions-url=https://launchermeta.mojang.com/mc/game/version_manifest.json
mscs-versions-json=/opt/mscs/version_manifest.json
mscs-versions-duration=1440
mscs-lockfile-duration=1440
mscs-default-world=world
mscs-default-port=25565
mscs-default-ip=
mscs-default-version-type=release
mscs-default-client-version=$CURRENT_VERSION
mscs-default-client-jar=$CLIENT_VERSION.jar
mscs-default-client-url=https://s3.amazonaws.com/Minecraft.Download/versions/$CLIENT_VERSION/$CLIENT_VERS$
mscs-default-client-location=/opt/mscs/.minecraft/versions/$CLIENT_VERSION
mscs-default-server-version=$CURRENT_VERSION
mscs-default-server-jar=minecraft_server.$SERVER_VERSION.jar
mscs-default-server-url=https://s3.amazonaws.com/Minecraft.Download/versions/$SERVER_VERSION/minecraft_se$
mscs-default-server-args=nogui
mscs-default-initial-memory=128M
mscs-default-maximum-memory=2048M
mscs-default-server-location=/opt/mscs/server
mscs-default-server-command=$JAVA -Xms$INITIAL_MEMORY -Xmx$MAXIMUM_MEMORY -jar $SERVER_LOCATION/$SERVER_J$
mscs-backup-location=/opt/mscs/backups
mscs-backup-log=/opt/mscs/backups/backup.log
mscs-backup-duration=15
mscs-log-duration=15
mscs-detailed-listing=motd server-ip server-port max-players level-type online-mode
mscs-enable-mirror=0
mscs-mirror-path=/dev/shm/mscs
mscs-overviewer-bin=/usr/bin/overviewer.py
mscs-overviewer-url=http://overviewer.org
mscs-maps-location=/opt/mscs/maps
mscs-maps-url=http://mc.simb.ch
``

mscs.properties
``
mscs-enabled=true
mscs-server-version=1.13
mscs-client-version=1.13
``

**Comment by IamSAB** [comment]
/opt/mscs
```
drwxr-xr-x  8 minecraft minecraft  4096 Okt  9 08:15 .
drwxr-xr-x  6 root      root       4096 Mai  2 14:16 ..
drwxr-xr-x 14 minecraft minecraft  4096 Okt  7 20:01 backups
-rw-------  1 minecraft minecraft    23 Jan 21  2017 .bash_history
drwxr-xr-x  3 minecraft minecraft  4096 Dez 26  2016 maps
drwxr-xr-x  3 minecraft minecraft  4096 Nov 21  2016 .minecraft
-rw-r--r--  1 minecraft minecraft  1543 Nov 22  2016 mscs.defaults
drwxr-xr-x  2 minecraft minecraft  4096 Okt  8 14:16 server
drwxr-xr-x  2 root      root       4096 Nov 28  2016 textures
-rw-rw-r--  1 minecraft minecraft 93100 Okt  9 08:15 version_manifest.json
-rw-r--r--  1 minecraft minecraft 93100 Okt  7 20:23 version_manifest.json.bak
drwxr-xr-x 14 minecraft minecraft  4096 Okt  9 08:15 worlds
```
/opt/mscs/server
```
drwxr-xr-x 2 minecraft minecraft     4096 Okt  8 14:16 .
drwxr-xr-x 8 minecraft minecraft     4096 Okt  9 08:15 ..
-rw-r--r-- 1 minecraft minecraft  9720769 Mai  3  2017 minecraft_server.1.11.1.jar
-rw-r--r-- 1 minecraft minecraft  9713666 Nov 14  2016 minecraft_server.1.11.jar
-rw-r--r-- 1 minecraft minecraft 30222121 Apr  2  2018 minecraft_server.1.12.2.jar
-rw-r--r-- 1 minecraft minecraft 30202458 Apr  2  2018 minecraft_server.1.12.jar
-rw-r--r-- 1 minecraft minecraft        0 Okt  8 14:13 minecraft_server.1.13.1.jar
-rw-r--r-- 1 minecraft minecraft        0 Okt  8 14:16 minecraft_server.1.13.jar
-rw-r--r-- 1 minecraft minecraft  2061638 Sep 18  2016 minecraft_server.1.4.7.jar
-rw-r--r-- 1 minecraft minecraft  8320755 Mai  3  2017 minecraft_server.1.8.9.jar
```

**Comment by sandain** [comment]
Just an idea here:

Try blanking `mscs-default-server-url` and `mscs-default-client-url` to match the current default versions.  These values are now extracted from an url listed in the `version_manifest.json` file.  In other words, change your `mscs.defaults` to look like:

```
mscs-default-server-url=
mscs-default-client-url=
```

**Comment by sandain** [comment]
Also, delete the empty files in /opt/mscs/server
```
rm minecraft_server.1.13.1.jar minecraft_server.1.13.jar
```

**Comment by sandain** [comment]
I don't know what the `textures` folder holds, but you may have better results if that folder is owned by your minecraft user.
```
sudo chown -R minecraft:minecraft /opt/mscs/textures
```
This however is not related to your current issue...

**Comment by sandain** [comment]
I'm leaving on vacation later today, so hopefully this solves your issue!  I'll try to check back, but I'll have limited connectivity.

**Comment by sandain** [comment]
I just pushed commit 0a1c07ba8b1c8d828330808a26c0596098811ec5 to fix the documentation issue here.

**Comment by IamSAB** [comment]
Thanks for the tips. I downloaded the jar myself into the `server` directory with
`sudo wget https://launcher.mojang.com/v1/objects/fe123682e9cb30031eae351764f653500b7396c9/server.jar` (same url as created with your command)
and then renamed it to mincraft_server.1.13.2.jar
After that I could start the world with the version 1.13.2 as this is the latest stable version.

The empty files are created from mscs. I think there not filled because the download fails.

**Comment by sandain** [comment]
I'm back from vacation.

Make sure that you have `liblwp-protocol-https-perl` installed as well as noted in Issue #194. This may be part of the problem.

Please test again with your `mscs.defaults` file modified as suggested and this package installed.  You can delete (or temporarily rename) the `mincraft_server.1.13.1.jar` file that you manually downloaded.  If it is working with these changes, either close this issue or let me know and I can do it.

Thanks for the bug report!

**Comment by IamSAB** [comment]
`liblwp-protocol-https-perl` is already installed.

I copied the mscs.defaults from the README and replaced my with its content. Now it works ...
I think the problem was the filled  `mscs-default-server-url=` which is now not set (before it had the value `https://s3.amazonaws.com/Minecraft.Download/versions/$SERVER_VERSION/minecraft_server`).
But as I know I never changed this, was there from installation (was a while ago ...).

**Comment by sandain** [comment]
Good, I'm glad changing the server URL worked.  I'm going to go ahead and close this issue. Thanks for the bug report
