### ISSUE TITLE
Help with message when restarting

### ISSUE THREAD

**Issue by hornta** [MinecraftServerControl/mscs#204]
When I type /mscs restart XXX I get the following message everytime. How can I prevent this from coming up and what does it really do?

find: Failed to restore initial working directory: /root: Permission denied
The version manifest cache was out of date, it has been removed.
Downloading current Minecraft version manifest.

**Comment by Roflicide** [comment]
You're running the `mscs` command in your root folder and that's why you're getting the permission denied error. 

`cd` anywhere else that's not within the root folder and run the `mscs` command to avoid that error

**Comment by sandain** [comment]
Hi @hornta.  Sorry for my slow response, I must have missed this issue.  I hope you were able to figure out the issue you were experiencing!  If not, please give us some more information on how you installed MSCS.  Did you follow the directions listed in the [README](https://github.com/MinecraftServerControl/mscs/blob/master/README.md#installation)? If you followed these directions and are still getting this error, please let me know and I'll try to help you figure out what is wrong -- you should not be getting permission issues!
