### ISSUE TITLE
syntax error at -e line 5, near "${}"

### ISSUE THREAD

**Issue by shawnbyday** [MinecraftServerControl/mscs#211]
Updated to latest version today. I found issue #198 but setting the default URL didn't work for me.

While trying to start my world:

`shawn@play:~/mscs$ sudo mscs start gtnh
The cached copy of the version manifest is up to date.
Use the force-update option to ensure a new copy is downloaded.
Starting Minecraft Server: gtnhsyntax error at -e line 5, near "${}"
Execution of -e aborted due to compilation errors.
Error detecting the current Minecraft version.`

Then I receive this error when trying to use the force update:

`shawn@play:~/mscs$ sudo mscs force-update gtnh
Removing cached version manifest.
Downloading current Minecraft version manifest.
Stopping Minecraft Server:.
Backing up Minecraft Server: gtnh.
Removing Minecraft Server software: gtnhsyntax error at -e line 5, near "${}"
Execution of -e aborted due to compilation errors.
syntax error at -e line 5, near "${}"
Execution of -e aborted due to compilation errors.
.
Updating Server Software: gtnhsyntax error at -e line 5, near "${}"
Execution of -e aborted due to compilation errors.
Error detecting the current Minecraft version.
`

**Comment by sandain** [comment]
Ahh shoot. I should have tested commit c6d0b591740541a2dab83c308443e8b757c9ae71... I just assumed it would work. Sorry about that.  I'll work on a fix asap.

**Comment by shawnbyday** [comment]
No worries, thanks for the quick reply! :D

**Comment by sandain** [comment]
This should be fixed by commit ea24167612fdeffeea86e026660f266bb1ed9850. Let me know how it works for you @shawnbyday

**Comment by shawnbyday** [comment]
Looks good now, thanks for the quick fix! Can close.

**Comment by sandain** [comment]
Closing the issue as fixed.  Thanks for reporting the issue @shawnbyday
