### ISSUE TITLE
Broken mscs-server-version parsing

### ISSUE THREAD

**Issue by Yax** [MinecraftServerControl/mscs#216]
MSCS doesn't accept valid version IDs is  `mscs.properties`:
```
mscs-server-version=1.14.2 Pre-Release 3
```
Result:
```
Starting Minecraft Server: worldCan't find string terminator '"' anywhere before EOF at -e line 3. 
```
Adding `"` around ID doesn't help.

This issue is related to #208. Mojang confirmed that version IDs can have spaces: https://bugs.mojang.com/browse/MC-147870 - bug report has `Works As Intended` status.

**Comment by sandain** [comment]
Hi @Yax.

With the changes made in PR #210, I bet it would work if you use something like:
```
mscs-server-version=1.14.2-Pre-Release-3
```

That said, the `getServerVersion()` and `getClientVersion()` methods need to be updated to work with spaces as was done in PR #210. I'll try to work on this over the weekend.

**Comment by sandain** [comment]
This should now be working as expected with commit e220b81d3d1bff33ce588fbf40faeaefb32ea593.  

@Yax, please let me know if you still experience issues with versions after updating. Thank you for submitting the issue.

**Comment by sandain** [comment]
Closing this issue as fixed.
