### ISSUE TITLE
Crontab mapping does nothing

### ISSUE THREAD

**Issue by Laikar** [MinecraftServerControl/mscs#217]
Manual mapping 
`mscs map` from console with regular and minecraft user works, but when automated in crontab
`sudo crontab -e -u minecraft`
`* * * * * mscs map` and `* * * * * mscs map >/mc/overviewerlog.txt`
(* * * * *) for testing purposes
Nothing happens
redirecting the output of the command to a log file writes this:
```
The cached copy of the version manifest is up to date.
Use the force-update option to ensure a new copy is downloaded.
Running Minecraft Overviewer mapping: spigotDotMoeError downloading the Minecraft client software.  
```
And nothing in overviwer.log

**Comment by sandain** [comment]
As the [README ](https://github.com/MinecraftServerControl/mscs#scheduling-backups)mentions for backups, you probably need to define HOME and PATH prior to the mapping command:
```
# Define HOME and PATH
HOME=/opt/mscs
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Run the mapping program
* * * * * mscs map
```

Let me know if that works for you.

**Comment by Laikar** [comment]
I already did, this si how my crontab looks, everything works but the mapping 
HOME=/mc/home
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin


```
# m h  dom mon dow   command
# Define HOME and PATH
HOME=/mc/home
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Run mscs backups
55 1 * * * mscs send spigotDotMoe say En 5 minutos el servidor realizara una copia de seguridad, se reiniciara y actualizara el mapa web.
56 1 * * * mscs send spigotDotMoe say Seguramente tarde unos 5 min en estar activo otra vez.
0 2 * * * mscs backup
1 2 * * * mscs restart
2 2 * * * mscs map

```
i changed all of the references to /opt/mscs to /mc/home, and backup works, so i highly doubt its that

**Comment by sandain** [comment]
The download error has me wondering if that is part of the problem. Have you tried updating the script again today?  I made some changes that may fix that issue.

Otherwise, I'm guessing that it is a path issue.
Is `overviewer.py` accessible from one of those paths?
What is the output of `which overviewer.py` from your minecraft user?
What is the output of `echo $PATH` from your minecraft user?

**Comment by Laikar** [comment]
Nevermind, i had a typo in the home directory that caused this, now everything is working allright, thanks for your help
