### ISSUE TITLE
automate loading world into ramdisk

### ISSUE THREAD

**Issue by m4lfuncti0n** [MinecraftServerControl/mscs#224]
automate enabling/disabling running the server on a RAM disk (similar to how [msm](http://msmhq.com/docs/commands/server.html) used to). should also dump the world periodically back to disk in case of unexpected events (power loss, system crashes etc).

**Comment by zanix** [comment]
Check out the options in the readme for [Adjusting global server properties](https://github.com/MinecraftServerControl/mscs#adjusting-global-server-properties)
The options `mscs-enable-mirror` and `mscs-mirror-path` as well as their ["default" counterparts](https://github.com/MinecraftServerControl/mscs#adjusting-global-server-properties) can be enabled for this exact feature. Then you will want to use the `sync` command (See [Command reference](https://github.com/MinecraftServerControl/mscs#command-reference)) to periodically sync to disk probably using a cron job.

**Comment by sandain** [comment]
@m4lfuncti0n, are the `mscs-enable-mirror` and `mscs-mirror-path` options and the `sync` command enough to get you what you need? Otherwise, please describe the missing feature in a little more detail.

**Comment by sandain** [comment]
Since I we haven't heard back, I'm going to assume that @m4lfuncti0n is happy with the features already in place for loading and syncing a world server to a ramdisk, and close this issue.
