### ISSUE TITLE
Switch docs to github pages

### ISSUE THREAD

**Issue by Roflicide** [MinecraftServerControl/mscs#231]
Hi @sandain @zanix ,

Hope you guys are doing well, it's been a while :) 

What do you guys think about putting the documentation on [Github Pages](https://pages.github.com/) ? I saw a few projects with that and I think its much more friendly than just a readme. I'd be happy to switch the content over, I just don't have permission to enable the feature in the repository (Settings tab > Github Pages section). And we could still include the readme in the project for people that want to view it on their local computer.

Thoughts?

**Comment by sandain** [comment]
I added a new repo: https://github.com/MinecraftServerControl/MinecraftServerControl.github.io with a basic `index.html` to start with.  It is accessible from https://minecraftservercontrol.github.io/

**Comment by sandain** [comment]
Let me know if you don't have write access to that repo.

**Comment by zanix** [comment]
Good idea

**Comment by Roflicide** [comment]
Please see https://minecraftservercontrol.github.io/ for the docs "2.0". Most of the content is the same as the current README. My goal was to make a clean, easy to navigate site since the current README is a bit dense and hard to navigate. I also expanded upon some sections and condensed others. 

Let me know what you guys think and any feedback you have. Thanks, happy new year!

**Comment by zanix** [comment]
I only took a quick look but it looks pretty good.

**Comment by sandain** [comment]
It looks good, nice job @Roflicide.  The only change I might do now is to incorporate the logo into the "Home" page.

What is your plan for the README now? Should we just make it point to the new "docs 2.0" and remove the rest?

**Comment by Roflicide** [comment]
@sandain I opened pull request #236 that updates the readme
