### ISSUE TITLE
mscs-jvm-args can't contain spaces

### ISSUE THREAD

**Issue by zdimension** [MinecraftServerControl/mscs#240]
If it does, the `start` command fails because the args aren't properly passed to perl, which read something like this:

    -XX:Arg1 -XX:Arg2

as 

    perl -ne '....... -XX:Arg1' -XX:Arg2

giving the error

    Unrecognized switch: -:Arg2    (-h will show valid options).

Problem is in file `msctl`, in `getServerCommand` when inserting the `$JVM_ARGS` variable in the perl call

**Comment by sandain** [comment]
Sorry for the slow response.  Commit 7c4b4545c07e273a815135fc04c4d1ee3a140f1b should fix this issue.
