### ISSUE TITLE
removing world

### ISSUE THREAD

**Issue by devinsdiabetes** [MinecraftServerControl/mscs#243]
I am having trouble removing a world file.

**Comment by sandain** [comment]
Hi @devinsdiabetes. Did you try using the `delete` command? See the [docs](https://minecraftservercontrol.github.io/docs/mscs/command-reference) for more info.

```
$ mscs status
Minecraft Server Status:
  alpha: running version 1.15.2 (0 of 20 users online).
    Process ID: 1486865.
    Memory used: 1288988 kB.
$ mscs delete alpha
$ mscs status
Minecraft Server Status:
```
