### ISSUE TITLE
Minecraft Overviewer software not found.

### ISSUE THREAD

**Issue by Nissenice** [MinecraftServerControl/mscs#247]
When I try to run 
`$ mscs map`
I get the message
`Minecraft Overviewer software not found.`

I'm running Ubuntu server and wasn't able to install Overviewer through apt so I built it from source. Then I entered the full path to `overviewer.py` into `mscs.defaults`. Like this:
`; Location of Overviewer.`
`# mscs-overviewer-bin=/home/ubuntu/Minecraft-Overviewer/overviewer.py`

I am able to run overviewer using
`$ python3 /home/ubuntu/Minecraft-Overviewer/overviewer.py`
so the path seems to be right.

I don't know what I'm doing wrong. I'm kind of new to this.

**Comment by zanix** [comment]
Try removing the `#` from the beginning of `mscs-overviewer-bin...`

**Comment by Nissenice** [comment]
> Try removing the `#` from the beginning of `mscs-overviewer-bin...`

Oh my god! I feel stupid. 
Thank you!

**Comment by DomesticMiku** [comment]
> Try removing the `#` from the beginning of `mscs-overviewer-bin...`

I have the same problem, but this solution haven't helped me(

**Comment by zanix** [comment]
Could you please open a new issue since this one is closed?
