### ISSUE TITLE
Access denied exception

### ISSUE THREAD

**Issue by DependentMacaroon** [MinecraftServerControl/mscs#252]
When starting the server, it fails with this message: Failed to start the minecraft server java.nio.file.AccessDeniedException: ./UbuntuCraft/session.lock
It worked fine until I installed Forge, maybe thats the issue.
Running a 1.16.1 server with the latest forge version. No mods installed.

**Comment by zanix** [comment]
I would check your file permissions and that they are owned by the mscs user `minecraft`
If not, run `chown -R minecraft:minecraft /opt/mscs/worlds/name`

**Comment by sandain** [comment]
@DependentMacaroon: Hopefully you figured out the permission issues you were having.  I'm going to close this issue, but feel free to reopen it if needed.
