### ISSUE TITLE
Better default shell for minecraft user

### ISSUE THREAD

**Issue by Omig12** [MinecraftServerControl/mscs#259]
Maybe running this command after creating the default minecraft user: `usermod --shell /bin/bash Minecraft`

This would enable the user to be able to lookup a history of commands by pressing up, allows them to fix typos and other QOL improvements when using the minecraft user.

**Comment by sandain** [comment]
Sorry. I feel that having the minecraft user as a limited system user is a good thing for security reasons.  Feel free to make the changes to your local user config if you like.
