### ISSUE TITLE
Overviewer Case Sensitivity Issue

### ISSUE THREAD

**Issue by Xarius86** [MinecraftServerControl/mscs#265]
Overviewer does not like generating maps due to cAsE sENsitiVITY. The first letter of my server was capitalized for whatever reason. (Not sure why I did that.) 

It looks for the backup in: /opt/mscs/backups/myserver/myserver
But, due to the capitalization, the actual backup folder is: /opt/mscs/backups/myserver/Myserver

Changing this in overviewer-settings.py is easy enough, but figured you'd want to be aware of it.

**Comment by sandain** [comment]
Hi @Xarius86, I'll try to look into this issue.  I find it odd that it's not in `/opt/mscs/backups/Myserver/Myserver` if you originally capitalized it.  Is this an imported world by chance, i.e., did you not use mscs to generate it?

**Comment by Xarius86** [comment]
I did use mscs to generate the world. But, it is possible I changed something accidentally. I'm going to mark this closed for now unless I notice something like it happen again.
