### ISSUE TITLE
PaperMC Setup Docu outdated

### ISSUE THREAD

**Issue by Killerbear** [MinecraftServerControl/mscs#270]
On the documentation for mscs to [setup a PaperMC Server](https://minecraftservercontrol.github.io/docs/mscs/adjusting-world-server-properties/papermc) the mscs-server-url is linking to an outdated download page.
```
mscs-server-url=https://papermc.io/ci/job/Paper-$SERVER_VERSION/lastSuccessfulBuild/artifact/paperclip.jar
```
According to the [documentation of PaperMC](https://paper.readthedocs.io/en/latest/site/api.html) this needs to be
```
mscs-server-url=https://papermc.io/api/v1/paper/$SERVER_VERSION/latest/download
```

**Comment by zanix** [comment]
Thanks!
If you are feeling up to it, you can update the documentation and submit a pull request here
https://github.com/MinecraftServerControl/MinecraftServerControl.github.io

**Comment by Killerbear** [comment]
sure.
i was already looking for it but couldnt find it.
PR is open.
