### ISSUE TITLE
Map does not generate

### ISSUE THREAD

**Issue by glasserd17** [MinecraftServerControl/mscs#272]
When I run mscs map I get the following output:
```
The cached copy of the version manifest is up to date.
Use the force-update option to ensure a new copy is downloaded.
Running Minecraft Overviewer mapping: Myserver.
```

The last line returns in less than a second. There are no error message on the console and although /opt/mscs/maps/Myserver/ exists, there are no files in that folder. I did run the backup command first.

I'm running Ubuntu 20.04 and downloaded the Overviewer deb file from https://overviewer.org/downloads and installed with:
```
sudo dpkg -i /path/to/deb/file
sudo apt-get install -f
```
I can't locate any log files for this process and I'm pretty puzzled as to what is going on - any help would be appreciated.

**Comment by sandain** [comment]
Hi @glasserd17.  You are running into an issue with they way the Overviewer folks are distributing their Debian builds.  They only provide a single deb file to support all versions of Debian, Ubuntu, and derivatives of the two.  However, starting with Ubuntu 20.04 (or maybe 19.10, I don't remember), there are enough changes to the python stack that this way of doing things is now broken.

Unfortunately, you will need to compile Overviewer yourself. You can't use the precompiled binary that they supply. I think these directions will walk you through the process: http://docs.overviewer.org/en/latest/building/

Good luck!

**Comment by zanix** [comment]
When I updated the docs last I assumed the binary downloads worked, guess out docs need to be updated again.

**Comment by glasserd17** [comment]
Thanks for the quick reply. I compiled myself and I'm still running into the same problem.

I ran 
```
python3 setup.py build
python3 setup.py install
```

which put `overviewer.py` into ` /usr/local/bin/`.  

`mscs.defaults` has this line

```
mscs-overviewer-bin=/usr/local/bin
```

It *seems* like this should work, but there are no error messages to help debug. Is there any way to get a more verbose output of what is happening?

**Comment by sandain** [comment]
Make that
```
mscs-overviewer-bin=/usr/local/bin/overviewer.py
```
Make sure overviewer is working by running the program in your worlds directory if that doesnt work

**Comment by glasserd17** [comment]
That was the problem. Thanks for your help! Maybe `https://minecraftservercontrol.github.io/docs/mscs/mapping` should be updated to indicate that the filename is needed?

**Comment by zanix** [comment]
PR to update the docs is here MinecraftServerControl.github.io/pull/5

Also, closing
