### ISSUE TITLE
PaperMC Update Method Deprecated

### ISSUE THREAD

**Issue by Xarius86** [MinecraftServerControl/mscs#273]
PaperMC no longer allows access to CI. You must use the new API for updates. How should we be configuring our _mscs.properties_ to accommodate this change?

New API: https://papermc.io/api/docs/swagger-ui/index.html?configUrl=/api/openapi/swagger-config

**Comment by zanix** [comment]
There is already a PR to change the docs MinecraftServerControl/MinecraftServerControl.github.io/pull/4
I will merge it now

**Comment by zanix** [comment]
PR was merged, closing

**Comment by Xarius86** [comment]
The documentation update is not accurate. It does not produce a working setup.

**Comment by sandain** [comment]
Hi @Xarius86. If you have the chance, would you be able to submit a PR to update the docs to make them more accurate?

**Comment by Xarius86** [comment]
@sandain I will have to take a look at your source code to see how you guys are handling the download URL. 
(The problem here is that you are expecting it to return "paperclip.jar" and it won't do that any longer with the new API. It is now returning "paper-VERSION-BUILD.jar")

I'll take a look at your code once I'm back in front of a desktop. Shouldn't be too difficult to get it working properly again.

**Comment by sandain** [comment]
The update function in the script is probably insufficient to install or update anything but the Mojang/Microsoft supplied server jar at this time. I submitted issue #261 with the hopes that I or someone else would have time to submit changes to fix this problem with alternative server solutions.  For the time being, I would update the documentation to demonstrate how to install/update using a manual method.  If you are interested in submitting something for #261, that would be great too!

**Comment by sandain** [comment]
The PaperMC v2 API does not provided a latest target, and they [closed an issue asking for one to be added back in](https://github.com/PaperMC/bibliothek/issues/3).  I have updated our documentation to show how to get a working PaperMC server.

Issue #261 tracks the need for a more robust update function that could fix this problem on our end since they refuse to do it on their end.  I'm going to close this issue.
