### ISSUE TITLE
Multiple server problem with local user

### ISSUE THREAD

**Issue by atomicecho** [MinecraftServerControl/mscs#278]
Hi,
I have two servers running on port 25565 and 25566 on an Ubuntu 20.04 system. When someone plays the server from the local machine the server not being played stops. This has not always been the case. So not sure whether I need to backup the worlds and totally reinstall, or if there might be an easier fix.
Thanks

**Comment by sandain** [comment]
Hi @atomicecho.  Please post a copy of the console.out file for the world server that stops. It should contain some information about what is going on.

**Comment by atomicecho** [comment]
I had a look - everything looks fine then it just says "Killed". I think it's because i was running out of RAM, I only had 8Gb installed. So I have now updated it to 16Gb and hopefully it has solved the problem. Thanks for your offer of help though.

**Comment by sandain** [comment]
That is what I was thinking was going on.  Glad you were able to figure it out.

**Comment by zanix** [comment]
Closing since it was fixed
