### ISSUE TITLE
unable to import world

### ISSUE THREAD

**Issue by TheRanker** [MinecraftServerControl/mscs#279]
![image](https://user-images.githubusercontent.com/5889820/112361577-80562d80-8cb6-11eb-945d-d2eec59b0ea7.png)

it just tells me the directory doesn't contain a world.  it most certainly do, as its running currently in another screen. this is 1.16.5. i dont know what else to try .. ps. im using sudo just to hammer the command in and make sure it runs. i know im in as root lol also this is ubuntu 20.04 focal fisa.

**Comment by zanix** [comment]
The import command requires a full path to the directory, this should probably be added to the docs

**Comment by TheRanker** [comment]
> The import command requires a full path to the directory, this should probably be added to the docs

![image](https://user-images.githubusercontent.com/5889820/112366101-5bb08480-8cbb-11eb-8f94-eac0a90f6355.png)
 full path.. still same error. also did this for 5 hours yesterday.. used full paths there too. didnt work.

**Comment by sandain** [comment]
If you are in the folder that contains the `server.properties` file, the following should work:
```
mscs import . Val32Server 25565
```

The `.` means current folder.

**Comment by TheRanker** [comment]
> If you are in the folder that contains the `server.properties` file, the following should work:
> 
> ```
> mscs import . Val32Server 25565
> ```
> 
> The `.` means current folder.

![image](https://user-images.githubusercontent.com/5889820/112366549-e3968e80-8cbb-11eb-9352-84d1e62fe3ca.png)
 failed

**Comment by sandain** [comment]
Odd. let me go audit the code real quick and see if I can figure this out.  I don't have a test server right now (in the middle of a move), so I can't try this myself.

**Comment by sandain** [comment]
It looks like a permissions issue, I think. The command is failing at https://github.com/MinecraftServerControl/mscs/blob/main/msctl#L2641 which is checking to make sure that both `.` and `./server.properties` exist and are readable.

If you haven't already done so, try:
```
sudo mscs import . Val32Server 25565
```

**Comment by TheRanker** [comment]
> It looks like a permissions issue, I think. The command is failing at https://github.com/MinecraftServerControl/mscs/blob/main/msctl#L2641 which is checking to make sure that both `.` and `./server.properties` exist and are readable.
> 
> If you haven't already done so, try:
> 
> ```
> sudo mscs import . Val32Server 25565
> ```

![image](https://user-images.githubusercontent.com/5889820/112367787-53594900-8cbd-11eb-8e3e-6e555332a2a2.png)
 still same. :(

**Comment by sandain** [comment]
Could you provide the results of `ls -la` while in the world folder?

**Comment by TheRanker** [comment]
> Could you provide the results of `ls -la` while in the world folder?

![image](https://user-images.githubusercontent.com/5889820/112368008-94e9f400-8cbd-11eb-932a-84e207ce578c.png)

**Comment by sandain** [comment]
I don't see a `server.properties` file in that directory listing. Is it in the `serverconfig` folder?  This might be complicated if so...

**Comment by TheRanker** [comment]
the server.properties is not located within the world folder.....  its in the previous folder.. /home/theranker/minecraft/val32server/

**Comment by sandain** [comment]
You need to be in the same folder as the `server.properties` file when executing the import.

**Comment by TheRanker** [comment]
![image](https://user-images.githubusercontent.com/5889820/112368551-25c0cf80-8cbe-11eb-8b09-364a6b73c855.png)

**Comment by TheRanker** [comment]
Could you provide the results of ls -la while in the world folder?.

that was your questoin.. i followed ur directions.. i got you the listing in the world folder. as you asked.

**Comment by TheRanker** [comment]
server.properties is not located within the world folder.. never have been.  its seperate from world.

**Comment by sandain** [comment]
Sorry to confuse. You have world specific files (which absolutely includes the configuration file for the world, `server.properties`) mixed in with server files, so it is a little confusing

**Comment by TheRanker** [comment]
i have a minecraft folder .. called val32server... which i have a world created on called Val32Server  . it can be confusing if not use to it. lol

**Comment by TheRanker** [comment]
my server.properties is in my minecraft folder thats starts the jar.   it is not located within a world

**Comment by sandain** [comment]
Ok. Lets rule out the script and just test the section where the error happens. Try the following command in the same folder that contains the `server.properties` file:

```
if [ ! -d "." ] || [ ! -r "./server.properties" ]; then
  printf "Directory containing a Minecraft world was not provided.\n"
fi
```

**Comment by sandain** [comment]
> my server.properties is in my minecraft folder thats starts the jar. it is not located within a world folder... its basically in the main folder to start minecraft along with my startup scripts and such. which also contains the jar.. and folder for the world.
> 
> dont believe you mean to tell me to put the server.properties in the same folder that the world files are in.


no. don't make any changes to your config

**Comment by TheRanker** [comment]
> Ok. Lets rule out the script and just test the section where the error happens. Try the following command in the same folder that contains the `server.properties` file:
> 
> ```
> if [ ! -d "." ] || [ ! -r "./server.properties" ]; then
>   printf "Directory containing a Minecraft world was not provided.\n"
> fi
> ```

done... nothing appeared on screen.

**Comment by sandain** [comment]
ohh. something got messed up with the formatting of that command.  you are still stuck in the if statement.

Try this oneliner instead:
```
if [ ! -d "." ] || [ ! -r "./server.properties" ]; then printf "Directory containing a Minecraft world was not provided.\n"; fi
```
Note: you probably have to hit `ctrl-c` to get back to your normal prompt.

**Comment by TheRanker** [comment]
i cant paste.. i hate this ssh crap lol

**Comment by sandain** [comment]
ohh, let me shorten it!

```
if [ ! -d "." ] || [ ! -r "./server.properties" ]; then echo "error"; fi
```

**Comment by TheRanker** [comment]
got it entered.a nd came back to root again
no errors

**Comment by sandain** [comment]
Ok. that is the expected result.  If it had said error then we know something is wrong with that line.

However, this opens up the question of why that command works when you run it by hand, but fails when the script runs it!

I have a meeting to get to, so I can't help any more for a little bit.  I'll give this some thought though and probably ask you some more questions later.

**Comment by TheRanker** [comment]
> Ok. that is the expected result. If it had said error then we know something is wrong with that line.
> 
> However, this opens up the question of why that command works when you run it by hand, but fails when the script runs it!
> 
> I have a meeting to get to, so I can't help any more for a little bit. I'll give this some thought though and probably ask you some more questions later.

please by all means id love to get this worked out and fixed up. this sesems like a great way to setup some worlds and chron job some schedulted restarts.  cant use the setup if i gotta create a new world with it :(

**Comment by TheRanker** [comment]
is it looking in the server.properties for a specific location for the world name? like a perticular line? or statement?  mine is as follows...  level-name=Val32Server   located on line 21. if any of this helps ya when ur back at it :)

**Comment by sandain** [comment]
No, it is simply looking to make sure that the `server.properties` file exists at the location provided.  I don't currently understand where the problem is at...

**Comment by sandain** [comment]
Okay, short meeting.

Let's try a full path just because:
```
mscs import /home/theranker/minecraft/val32server Val32Server 25565
```

Try it with `sudo` if that doesn't work.

**Comment by zanix** [comment]
Can you show the entire directory structure for your entire minecraft folder?
Also, I notice there is a mscs folder in the same directory, did you install mscs using the make install or did you do the manual install?

**Comment by TheRanker** [comment]
> Can you show the entire directory structure for your entire minecraft folder?
> Also, I noticed there is a mscs folder in the same directory, did you install mscs using the make install or did you do the manual install, or is this just the git clone folder for the script?

the mscs was intially installed there. not realizing what folder i was in. 
tree structure is quite long. so here it goes. lol   i did the git clone folder in the mscs initially. 
![image](https://user-images.githubusercontent.com/5889820/112376975-1f375580-8cc8-11eb-886e-d0561399e896.png)
![image](https://user-images.githubusercontent.com/5889820/112377061-38d89d00-8cc8-11eb-9b8a-651267d627b8.png)
![image](https://user-images.githubusercontent.com/5889820/112377088-40984180-8cc8-11eb-93dd-f40ef8a2440d.png)
![image](https://user-images.githubusercontent.com/5889820/112377113-4a21a980-8cc8-11eb-85e2-28638526800a.png)
![image](https://user-images.githubusercontent.com/5889820/112377146-560d6b80-8cc8-11eb-9056-709f89943a44.png)
![image](https://user-images.githubusercontent.com/5889820/112377163-5dcd1000-8cc8-11eb-977d-c5c13b349e86.png)

**Comment by TheRanker** [comment]
> Okay, short meeting.
> 
> Let's try a full path just because:
> 
> ```
> mscs import /home/theranker/minecraft/val32server Val32Server 25565
> ```
> 
> Try it with `sudo` if that doesn't work.

same response, world folder not found :(
![image](https://user-images.githubusercontent.com/5889820/112378434-e39d8b00-8cc9-11eb-9c09-c046bc9f48b2.png)

**Comment by TheRanker** [comment]
to note.... Shift  + Insert .. is paste command. lol

**Comment by sandain** [comment]
Hmm.  I don't understand what is happening.  As far as I can tell, we are getting stuck where we shouldn't be...

Give me some more info on your setup.  How did you install mscs? Did you use the `make install` method?  What is the output of `which mscs`?

**Comment by TheRanker** [comment]
> Hmm. I don't understand what is happening. As far as I can tell, we are getting stuck where we shouldn't be...
> 
> Give me some more info on your setup. How did you install mscs? Did you use the `make install` method? What is the output of `which mscs`?

i did the dependiencies.. as i already had one or two. have webmin also installed.   then i did 
git clone https://github.com/MinecraftServerControl/mscs.git && cd mscs
sudo make install

basically followed the install guide for it all

**Comment by sandain** [comment]
Ok, great.  That should simplify things.  What is the output of:
```
which mscs
```

**Comment by TheRanker** [comment]
/usr/local/bin/mscs

**Comment by sandain** [comment]
It appears you are running all of these commands as root.  Have you tried using a normal user?

**Comment by TheRanker** [comment]
> It appears you are running all of these commands as root. Have you tried using a normal user?

im running it as root to avoid permission problems.  i have the minecraft user setup i can use that but may run into perm issues.

**Comment by zanix** [comment]
Maybe the minecraft files need to be owned by the mscs user (`minecraft`)?

**Comment by TheRanker** [comment]
> Maybe the minecraft files need to be owned by the mscs user (`minecraft`)?

that wouldnt matter if i ran it as root anyway.

**Comment by sandain** [comment]
Even if run by root, the `mscs` script calls everything using the `minecraft` user.

Try running these commands using your normal user, `theranker`.

**Comment by TheRanker** [comment]
> Even if run by `root`, the mscs script calls everything using the `minecraft` user.
> 
> Try running these commands using your normal user, `theranker`.

![image](https://user-images.githubusercontent.com/5889820/112387267-7ba07200-8cd4-11eb-9bae-b8e0e3e3b189.png)

**Comment by sandain** [comment]
I still think it is a permissions issue.  Try:
```
sudo chown -R minecraft:minecraft home/theranker/minecraft/val32server
```

**Comment by TheRanker** [comment]
> I still think it is a permissions issue. Try:
> 
> ```
> sudo chown -R minecraft:minecraft /home/theranker/minecraft/val32server
> mscs import /home/theranker/minecraft/val32server Val32Server 25565
> ```

RESOLVED~

**Comment by sandain** [comment]
holy cow. should have tried that to begin with. rofl.  Let's update those docs

**Comment by TheRanker** [comment]
i did run that command. may have had a typo and missed somethign lol

**Comment by zanix** [comment]
Where is the table flip emoji?

**Comment by sandain** [comment]
> 
> 
> Where is the table flip emoji?

(╯°□°)╯︵ ┻━┻

**Comment by sandain** [comment]
So @TheRanker, since it appears you appear to be using Forge, you will want to follow the directions at: https://minecraftservercontrol.github.io/docs/mscs/adjusting-world-server-properties/forge to get that setup as well.

**Comment by TheRanker** [comment]
> So @TheRanker, since it appears you are using Forge, you will want to follow the directions at: https://minecraftservercontrol.github.io/docs/mscs/adjusting-world-server-properties/forge to get that setup as well.

o no wories..already taken care of :D hahaha

**Comment by sandain** [comment]
Docs are updated to add the permissions step.
