### ISSUE TITLE
Forge Import / Load not workin successfully (loads vanilla)

### ISSUE THREAD

**Issue by TheRanker** [MinecraftServerControl/mscs#280]
Hello again ;)

so.. ive imported. edited the file to have forge version identifiers as listed in the setup. i didnt do the forge installer by whats in teh guide, as the modpack i use is provided with a forge installer that i install. java forge-1.16.5-36.1.2-installer.jar --installServer .  it does the install.. and puts the liberaries where they are suppose to be located in the server directory.   when i run the world, it boots vanilla.  no mods are loaded, no forge loader or fml loader.  ive also noticed... upon importing the folder.. it generates an error that states cannot create a subfolder in a folder of the same name... but all files are copied over.  
'
in loading process by using the watch command, all you see is recipe errors flying up the screen. then it just stops and does nothing else.   i may have somethign setup wrong . im not sure.. eyes gone after working on pc all day. any help or advice would be greatly appricated :D lol

do the minecraft server jar have to be in its own directory if its not indicated to be there? my forge i use in modpack updates weekly. 

these are in my mscs.properties of the world.
mscs-enabled=true
mscs-client-version=1.16.5
mscs-server-version=1.16.5
mscs-server-jar=minecraft_server.1.16.5.jar
mscs-server-url=
mscs-initial-memory=4096M
mscs-maximum-memory=12288M

**Comment by zanix** [comment]
From your last issue, I think you still have the jar files in the world directory (`/opt/mscs/worlds/Val32server`) so `mscs-server-jar` is pointing to the wrong file.
If you don't want to move the server files, I think you can set `mscs-server-jar=/opt/mscs/worlds/Val32server/forge-1.16.5-36.1.2.jar`

If you want the server files where the mscs docs suggest they go, you could move all of the `forge-1.16.5-36.1.2*` files, `minecraft_server.1.16.5.jar`, `1.16.5.json`, and the `libraries` folder into `/opt/mscs/server/forge-1.16.5-36.1.2`
Then in `mscs.properties` set `mscs-server-jar=forge-1.16.5-36.1.2/forge-1.16.5-36.1.2.jar`

Normally (in mscs) the forge server files are installed to `/opt/mscs/server/forge-1.16.5-36.1.2/forge-1.16.5-36.1.2.jar` as well as the `libraries` folder

Also, make sure the entire mscs folder is owned by the minecraft user after you move things around
`sudo chown -R minecraft:minecraft /opt/mscs`

**Comment by TheRanker** [comment]
alright.. as an update.. for another hour of troubleshooting.. it has to be in a folder.. it will not work if ran from server directory no matter what directory path you give the server and jar.  resolved the issue by creating a folder within server to place all the necessary files.. also.. 1.16.5.json .. should be notified to put that in the forge jar folder or forge wont load. it'll be vanilla as well. when you import, it is in the world folder. or depending on your host could be in god knows what folder. lol my server and services are all finally up and running 100% . and ill gladly help anyoen who had similar issues :)

**Comment by TheRanker** [comment]
Fixed by designating a forge server to hold the necessary files. Don't work in server folder
