### ISSUE TITLE
Non-issue, general inquiry

### ISSUE THREAD

**Issue by TheRanker** [MinecraftServerControl/mscs#281]
I am wondering if there is a way I can edit the displayed message upon restart of a forge server   it currently displays admin initiated server restart.  I have auto restarts on and I'd like for it to display auto restart active . Restarting in ......  Also leads to next question, can the timer be changed?

Thanks so much for this freakin awesome service.

**Comment by zanix** [comment]
You will need to edit the `msctl` file directly in `/usr/loca/bin/`

The restart function starts here https://github.com/MinecraftServerControl/mscs/blob/main/msctl#L2572
The 3 `sendCommand` lines and the `sleep` command are where you are looking for here:
https://github.com/MinecraftServerControl/mscs/blob/main/msctl#L2604

**Comment by TheRanker** [comment]
> You will need to edit the `msctl` file directly in `/usr/local/bin/`
> 
> The restart function starts here https://github.com/MinecraftServerControl/mscs/blob/main/msctl#L2572
> The 3 `sendCommand` lines and the `sleep` command are where you are looking for here:
> https://github.com/MinecraftServerControl/mscs/blob/main/msctl#L2604

God bless ur Cotten socks haha

**Comment by TheRanker** [comment]
Info to update server-restart notifications - resolved
