### ISSUE TITLE
Created new world , now restart script don't work

### ISSUE THREAD

**Issue by TheRanker** [MinecraftServerControl/mscs#284]
Hey guys. I had a perfectly working auto restart with a Cron job for every 8 hours on my server. Gave countdown and advised everyone of a restart commencing .    Created a new world , it auto restarts it as scheduled. But immediately restarts. No prompt or anything anymore. :( My mscsctl has the proper setup and nothing changed in it. Dunno what's breaking it. Any advise is greatly appreciated. Thanks guys

**Comment by zanix** [comment]
If you edited the section I mentioned in `msctl`, can you post it here?

**Comment by TheRanker** [comment]
I can. And yes I did. And it worked ever since.  No issues at all.   Then created new worldnusing mscs create.  And it don't work no more but it all remains the same

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by zanix** [comment]
Does your cron call each world separately?
```shell
mscs restart <world>
```
Or do you restart all of them in one command?
```shell
mscs restart
```

**Comment by TheRanker** [comment]
My Cron calls the world mscs restart NewVal33

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by TheRanker** [comment]
Precious worldnis disabled
________________________________

**Comment by TheRanker** [comment]
restart | reload | force-restart | force-reload)
    # Grab the latest version information.
    updateVersionsJSON
    # Figure out which worlds to restart.
    if [ "$#" -ge 1 ]; then
      for arg in "$@"; do
        if isWorldEnabled "$arg"; then
          WORLDS="$WORLDS $arg"
        elif isWorldDisabled "$arg"; then
            printf "Unable to start the requested worlds: world '$arg' is disabled.\n"
            printf "Please enable the world first with '$PROG enable $arg'.\n"
            exit 1
        else
          printf "Unable to restart the requested worlds: world '$arg' not recognized.\n"
          printf "  Usage:  $PROG $COMMAND <world1> <world2> <...>\n"
          exit 1
        fi
      done
    else
      WORLDS=$(getEnabledWorlds)
    fi
    if [ -z "$WORLDS" ]; then
      printf "Unable to restart worlds: no enabled worlds found.\n"
      exit 1
    fi
    # Restart each world requested, start those not already
    # running.
    printf "Restarting Minecraft Server:"
    for WORLD in $WORLDS; do
      printf " $WORLD"
      if serverRunning $WORLD; then
        if [ $(queryNumUsers $WORLD) -gt 0 ]; then
          sendCommand $WORLD "say The server initiated a server auto-restart."
          sendCommand $WORLD "say The server will auto-restart in 3 minute..."
          sleep 60
	  sendCommand $WORLD "say The server will auto-restart in 2 minute..."
	  sleep 60
	  sendCommand $WORLD "say The server will auto-restart in 1 minute..."
	  sleep 60
          sendCommand $WORLD "say The server is now restarting."
        fi
        sendCommand $WORLD "save-all"
        sendCommand $WORLD "save-off"
        if [ "$(echo \"$COMMAND\" | cut -d '-' -f1)" = "force" ]; then
          forceStop $WORLD
        else
          stop $WORLD
        fi
        sleep 5
      fi
      start $WORLD
    done
    printf ".\n"
    ;;

**Comment by TheRanker** [comment]
# Define Home and Path
HOME=/opt/mscs
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Run mscs restart. remove# to activate
0 */8 * * *  mscs restart NewVal33

**Comment by zanix** [comment]
I hope you don't mind, but I edited your post with the script to have code tags so it's easier to read

**Comment by TheRanker** [comment]
restart is in 3 mins.. i just tossed ur edit into the msctl . lol

**Comment by zanix** [comment]
Are there any users logged into the world when it restarts?
There is a line to check if there are any users first otherwise it just restarts immediately.
`if [ $(queryNumUsers $WORLD) -gt 0 ]; then`

**Comment by TheRanker** [comment]
it restarts
thats not hte issue. 
just no prompts are given

**Comment by TheRanker** [comment]
![image](https://user-images.githubusercontent.com/5889820/114284484-d6eb9780-9a2a-11eb-91d6-5e8da23be90f.png)

no notifications was given. :(

**Comment by TheRanker** [comment]
i normally have an idea what might be causing it.. but i only created a new world.. and it dont work no more :(
the crontab runs it job. restarts.. but the restart script isnt prompting any notifications of restart.

**Comment by zanix** [comment]
I don't see anything wrong with your modifications, it should still work.
There is some some indentation using tabs not spaces, but that shouldn't affect it.

Can you try running `mscs send "say This is a test message"` and see if the message shows up?

**Comment by TheRanker** [comment]
i can confirm that do indeed work.

**Comment by zanix** [comment]
Well dang, that's the exact same command that outputs the messages.
Maybe the tabs vs spaces does matter? Although it should matter, might as well try changing those tabs to spaces.

Also, you can send to all active worlds using `mscs broadcast <command>` if you wanted to.

**Comment by TheRanker** [comment]
it worked before.. perfectly.. never got edited changed or modified in any way at all.  but will not work on my new world.


commands work. thats not an issue.

**Comment by zanix** [comment]
You created a new world, that is the difference. I wanted to check if a simple send command worked and that a test message would show up on this new world.

Just so I have this correct, if you run `mscs restart NewVal33` it restarts in 3 minutes but has no prompts in-game?
Does the the restart process, plus messages, work on another world?

**Comment by TheRanker** [comment]
root@vmi527064:~# mscs restart NewVal33
find: Failed to restore initial working directory: /root: Permission denied
The cached copy of the version manifest is up to date.
Use the force-update option to ensure a new copy is downloaded.
Restarting Minecraft Server: NewVal33

**Comment by TheRanker** [comment]
finally an error that could be used to resolve it.

**Comment by TheRanker** [comment]
find: Failed to restore initial working directory: /root: 
is the main cause of all of this.

**Comment by zanix** [comment]
Well dangit. I have to go in a few minutes so I won't be able to help.
One last thing I can think of, revert your changes and copy the msctl script from where you downloaded it to `/usr/local/bin/`, then try the restart command again.

As for the find command error, I'm not sure what that means.

Sorry I couldn't help fix it before I leave for the weekend.

**Comment by TheRanker** [comment]
im not reverting any changes man.. 30 palyers on this server

**Comment by zanix** [comment]
I'm just talking about the changes the msctl script.
Did you make other changes to it?

**Comment by TheRanker** [comment]
i never made ANY CHANGES.. NONE

**Comment by TheRanker** [comment]
did i make any other changes??? i never made a change yet ffs.

**Comment by zanix** [comment]
No need to get upset.

You added those additional sleep and sendMessage commands in the `restart | reload | force-restart | force-reload` section of the msctl script.
I was just suggesting that you copy over the original msctl script and try that to see if it worked with the prompts, although it would be only a 1 minute warning instead of 3.

I am sorry I am not able to help any further. I will check back when I get home in a few days.

**Comment by TheRanker** [comment]
ive added thaty month ago man

**Comment by TheRanker** [comment]
i went and re-assigned a chown for minecraft:minecraft... for the resposatory i downloaded 4 weeks ago... and the current mscs folder its operating out of. ...  didnt resolve anything.

**Comment by TheRanker** [comment]
and zanik .. i also downloaded and installed your msc-gui  ... all done and on the system..  no clue how to run it, view it.. see it, ,, operate it,, comamnd it... nothing . not a stitch of info anywhere on what to do with the thing onces you run your little install.  right now its sitting on the server.. doing nothing. cause no documentation on how to use it, or even what to do with the bloody thing once its installed.  pretty sad man.   Updated on Mar 6, 2016 given its been 5 years now and you didnt even include any help in using the bloody thing? its useless.

**Comment by zanix** [comment]
Sorry, here are the docs
https://minecraftservercontrol.github.io

**Comment by TheRanker** [comment]
> Sorry, here are the docs
> https://minecraftservercontrol.github.io
> 
> The link is kinda hidden on the main repo page

Ummm. U have no useage direction of that service. No commands no idea how to run it or what to do with it.  U have installation and info of what it's for... Nothing to do with it after installation. .

**Comment by zanix** [comment]
I didn't notice you said mscs-gui, I thought you were talking about the mscs script only.
mscs-gui is not in a complete state so there is no documentation and there haven't been much interest in it either.

**Comment by TheRanker** [comment]
I'll most on that GitHub for advice.  But this mscs restart isn't giving notifications. Cause it says the initial folder has no permissions. But damn thing works. Just not properly.    Make a uninstall and reinstall will fix. But I don't know how to do that with mscs on Ubuntu 20.04

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zanix** [comment]
cd into the directory where you cloned/downloaded the script and run `sudo make clean, that should remove the files

**Comment by TheRanker** [comment]
And just do the get clone part again after? Don't need to do the full setup or anything ? As the clone isn't in the same folder as mscs is running from

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zanix** [comment]
Correct, you would just be re-installing the script files from the folder where you downloaded the script.
The `/opt/mscs` folder is your data folder.
The makefile copies the script files to `/usr/local/bin` and some other files elsewhere, you can see what it does in the Makefile https://github.com/MinecraftServerControl/mscs/blob/main/Makefile

Looking the makefile closer, I think you could just run `sudo make update` and that should re-copy the files again.

**Comment by TheRanker** [comment]
Ok. So the repo I've downloaded before was in home/theranker/Minecraft.  And opt/mscs. And in the /use/bin.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by sandain** [comment]
@TheRanker, @Zanix and myself are not paid to help you. You have paid nothing for the work we have done. Your attitude is unwanted. MSC-GUI is a Proof -Of-Concept and is not meant for production servers.

I'm closing this issue as not our bug. User error.

**Comment by sandain** [comment]
I've banned @TheRanker from commenting for 7 days.  Additional abuse beyond that period will result in a permanent ban. I will not put up with this kind of abuse.
