### ISSUE TITLE
ERROR: Python not found! (despite being installed) RHEL 8

### ISSUE THREAD

**Issue by PixelDu5t** [MinecraftServerControl/mscs#289]
I tried to set this up on RHEL 8 following the instructions, and when trying to do `msctl create world 25565` I get an error:

`which: no python in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
ERROR: Python not found!
Try installing this with:
sudo apt-get install python`

I currently have Python 3.6.8 installed:

`[root@localhost mscs]# python3`
`Python 3.6.8 (default, Aug 18 2020, 08:33:21) `
`[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>>`

I managed to fix all the other dependancy problems by manually installing each one with yum, but I'm not sure what to do with this issue. Any clue what I could do here?

**Comment by zanix** [comment]
The uses `which python` for the executable location.
You can either add a symlink for `python` to the `python3` executable or you can edit `/usr/local/bin/msctl` and edit the line `PYTHON=$(which python)` to `PYTHON=$(which python3)`

**Comment by sandain** [comment]
Maybe we should change the `which python` to `which python3` in the script.  All of the dependencies (rdiff_backup and Overviewer) that require python are now using Python3 anyway..

**Comment by zanix** [comment]
Maybe? I just checked on some of the system I maintain and `python` is symlinked to `python3`.

**Comment by sandain** [comment]
I went ahead and made this change in commit 2cf086d0ae26694c298b598c72973e542059e0c3. The world has moved on to python3 for the most part, so I don't expect this to be an problem. Closing this issue as fixed.
