### ISSUE TITLE
Specifying different java versions per worlds

### ISSUE THREAD

**Issue by nooklyn1** [MinecraftServerControl/mscs#294]
Hello, 

Could be me but it looks like minecraft 1.16.5 and minecraft 1.17 can't be run on the same java version. I ran a modded and vanilla server on 1.16.5  in  the past without issue because these used the same java version. is there a way to specify for one of the servers which java version to use?

**Comment by zanix** [comment]
You can add `mscs-server-command` to the world's `mscs.properties` file.

The default for this setting is
```ini
mscs-server-command=$JAVA -Xms$INITIAL_MEMORY -Xmx$MAXIMUM_MEMORY $JVM_ARGS -jar $SERVER_LOCATION/$SERVER_JAR $SERVER_ARGS
```

Replace `$JAVA` with the path to the java runtime you need.

You can also alter this globally in `/opt/mscs/mscs.defaults`

```ini
mscs-default-server-command=$JAVA -Xms$INITIAL_MEMORY -Xmx$MAXIMUM_MEMORY $JVM_ARGS -jar $SERVER_LOCATION/$SERVER_JAR $SERVER_ARGS
```

These options and more are documented here: https://minecraftservercontrol.github.io/docs/mscs/adjusting-world-server-properties

**Comment by nooklyn1** [comment]
Thanks!
