### ISSUE TITLE
MSCS ignores .jar

### ISSUE THREAD

**Issue by Eisenbahn** [MinecraftServerControl/mscs#296]
Hi.
Recently the MSCS locked me somehow and i was kinda forced to update it, guess it was okay.
It prompted 'cant find process id' it was old java, I updated, works now.

But now everytime I try to run a bungee, mohist, forge, older spigot server, it ignores the config and starts 1.17 vanilla..

Ex of config:

mscs-enabled=true
mscs-server-jar=mohist-1.12.2.jar
mscs-initial-memory=2G
mscs-maximum-memory=3G
mscs-server-command=$JAVA -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=45 -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=35 -XX:G1MaxNewSizePercent=60 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=50 -Xms$INITIAL_MEMORY -Xmx$MAXIMUM_MEMORY -jar $SERVER_LOCATION/$SERVER_JAR $SERVER_ARGS

Defaults manifest is untouched too, path is alright.

I did tried puting the .jar path direct in this config, but no success :/

Peace!

**Comment by sandain** [comment]
Hi @Eisenbahn.  I'm not sure what the issue is without some more info. Please post a copy of the `console.out` file from a server that is not working as expected. While you are at it, please post the `mscs.properties` file for that server as well.
