### ISSUE TITLE
Forge Mods enabled

### ISSUE THREAD

**Issue by justincm** [MinecraftServerControl/mscs#298]
Is there a way to see if the mods have loaded in mscs forge?

Also would quoted mods e.g "Flan's Mod" be acceptable?

**Comment by zanix** [comment]
Forge itself would need to have a console command to list loaded mods. I tried to find that info but I was not able to see a list of commands.
I think Forge will output the list when it starts up so it might be in the log.

**Comment by sandain** [comment]
I could be wrong, but that appears to be a normal Mojang server.  Could you please provide the  `mscs.properties` file for this world?

**Comment by justincm** [comment]
mscs-enabled=true
mscs-client-version=1.12.2
mscs-server-version=1.12.2
mscs-server-jar=forge12/minecraft_server.1.12.2.jar
mscs-server-url=
mscs-initial-memory=1024M
mscs-maximum-memory=3048M

**Comment by justincm** [comment]
sorted

**Comment by justincm** [comment]
using forge file now and using java 8 for forge only

**Comment by justincm** [comment]
mscs-enabled=true
mscs-client-version=1.12.2
mscs-server-version=1.12.2
mscs-server-jar=forge12/forge-1.12.2-14.23.5.2855.jar
mscs-server-url=
mscs-initial-memory=1024M
mscs-maximum-memory=3048M
mscs-server-command=/usr/bin/java8 -Xms$INITIAL_MEMORY -Xmx$MAXIMUM_MEMORY $JVM_ARGS -jar $SERVER_LOCATION/$SERVER_JAR $SERVER_ARGS

**Comment by zanix** [comment]
Glad you got it all figured out.
And thanks for posting your solution.
