### ISSUE TITLE
Importing Pre-Made Server Packs - Workaround?

### ISSUE THREAD

**Issue by SailorJerrys** [MinecraftServerControl/mscs#299]
Howdy, just started using MSCS, and I'm pretty new with hosting servers through Linux command line, and even more new to using MSCS. But I do really like how simple it is!

Anyways, cutting to the chase: I recently set up a SevTech server, and wanted to make it a bit more automated, with the ability to access the console through mscs as opposed to fiddling about with getting 'services' working, (though I really should learn how to manage that, honestly.)

Importing didn't seem to cause any problems, though when I tried to import the world I would get an error (after it transferred everything fine) saying that mscs couldn't put a subfolder into itself? It seemed to want to create a folder called SevTech/SevTech/SevTech, don't think it's related to the problem but thought it was worth mentioning.

When I run the imported server, it doesn't load any mods and shows as a vanilla server, so that's a no-go. My next test was to make a fresh Forge instance and import all the mods manually by copying the folders over from the other world- Also a no go, I get endless errors and warnings on the server start, and when I try to connect I get a huge message dump in the console that I believe is saying I have no mods enabled. And it disconnects me immediately. Any ideas, thoughts?

Cheers!

**Comment by SailorJerrys** [comment]
Sorry, it doesn't say I have no mods enabled, it's a list of all the mods enabled on the client, the error client-side is "fatally missing registry entries".

**Comment by SailorJerrys** [comment]
[console out.txt](https://github.com/MinecraftServerControl/mscs/files/7172693/console.out.txt)

Here's the console file!

**Comment by sandain** [comment]
Hi @SailorJerrys. I haven't played around with a SevTech server, but I would imagine it is somewhat similar to setting up a Forge server.  The wiki [here ](https://minecraftservercontrol.github.io/docs/mscs/adjusting-world-server-properties/forge) has details.

Specifically, it shows how to install the server software with necessary libraries, and it shows where to place mods.

Looking through your console file, it appears that there are a lot of issues with non-mod files being in the mod folder and other issues mentioning missing libraries.  I'm guessing you need to rework your mod/library setup.

**Comment by SailorJerrys** [comment]
Yeah, that might be the case. Going to be a pain in the ass cause I don't really fully understand how mods work with servers and the like, only ever used server packs and played with mod packs, never built one piece by piece myself.
