### ISSUE TITLE
Server set up with Forge following documentation instructions, but starts as a vanilla server

### ISSUE THREAD

**Issue by ShardPerson** [MinecraftServerControl/mscs#303]
I'm very confused as to what's going on, I've got an MSCS install on a Linux Mint server that i control through XRDP, i installed openJDK 8 as per instructions for 1.16.5 servers, and then followed the documentation for MSCS with no errors happening at any point, made sure that the mscs.properties was properly set up and everything. 

But when I actually run the server, it just starts a vanilla server, as if it was loading minecraft_server.1.16.5.jar instead of the forge jar, just to test, i tried deleting that vanilla server jar, and it didn't change anything.

I don't know if it's of note, but there's also no .minecraft folder in my mscs isntall, so there's no client files, but the documentation doesn't say anything about how to make the .minecraft folder structure show up or if it's relevant to the actual server.

I don't currently have the server online (i'm posting from my phone) so i can't post the actual files but I went through the server logs and there's quite literally no mention of Forge, it's as if I was loading a vanilla 1.16.5 server.

I've considered editing the mscs.defaults file, but at this point i'm not sure it'd do anything. Should I be making changes to stuff elsewhere?

**Comment by zanix** [comment]
Are you possibly getting hit with this issue? #302

**Comment by zanix** [comment]
Oh, I just noticed the MSCS Forge docs were updated and that 1.16.5 doesn't have the changes...
https://minecraftservercontrol.github.io/docs/mscs/adjusting-world-server-properties/forge

**Comment by ShardPerson** [comment]
> Are you possibly getting hit with this issue? #302

Well I assumed since it's 1.16.5 and the docs say that the 1.17+ install works different, I'd think not, but at this point it doesn't hurt trying it, tomorrow i'll check stuff as soon as I can get some time.

From skimming the issue you linked though, I did notice, the forge Jar I got from the installer did *not* have a "universal" at the end, though i believe there might have been such a .jar in one of the directories in the library folder created by the installer.

**Comment by ShardPerson** [comment]
Upon further testing with a new server, it seems like mscs.properties is being ignored by mscs, i don't know what changed since i created the first server yesterday (which initially did create the folder structure of forge, with a mods folder included, though it did not run until i deleted OptiFine, after which it just ran as a vanilla server), but creating a server and modifying the mscs.properties file as indicated in the docs leads to a vanilla server, the file structure is that of a vanilla server, with no mods folder.

The fact that no debug option is included in mscs and that there's no debug logs means I can't tell what mscs is doing at all.

**Comment by sandain** [comment]
Hi @ShardPerson. I would need to see a copy of the `mscs.properties` for your Forge world, and perhaps an understanding of your file structure to help you debug this issue. If the `mscs.properties` file is being ignored, then it is likely not in the correct location. If you installed MSCS to the default location, you should have a `mscs.properties` file in `/opt/mscs/worlds/world_name/mscs.properties`.  If you have made changes to the `/opt/mscs/mscs.defaults` file, I would need to see that as well.

**Comment by ShardPerson** [comment]
> Hi @ShardPerson. I would need to see a copy of the `mscs.properties` for your Forge world, and perhaps an understanding of your file structure to help you debug this issue. If the `mscs.properties` file is being ignored, then it is likely not in the correct location. If you installed MSCS to the default location, you should have a `mscs.properties` file in `/opt/mscs/worlds/world_name/mscs.properties`. If you have made changes to the `/opt/mscs/mscs.defaults` file, I would need to see that as well.

I ended up nuking the entire Linux Mint install, starting from scratch following the same steps, and got it to work, I figure it might have just messed up at some point due to using XRDP since apparently there's issues with running things as root in XRDP, but on this second attempt it's worked so I dont know.

**Comment by sandain** [comment]
Good, I'm glad you got it working. Feel free to open a new issue if you have any problems using MSCS in the future.
