### ISSUE TITLE
Minecraft Overviewer software not found. Again!

### ISSUE THREAD

**Issue by DomesticMiku** [MinecraftServerControl/mscs#314]
I have the same problem as discribed in #247, but this solution haven't helped me
> Try removing the `#` from the beginning of `mscs-overviewer-bin...`

[mscs.txt](https://github.com/MinecraftServerControl/mscs/files/8748162/mscs.txt)

`$ python3 ~/Minecraft-Overviewer/overviewer.py`
works properly and calls overviewer script, so I don't have any clues

**Comment by DomesticMiku** [comment]
I so stupid, my folder with script is in `/home`, so other users don't have permission to execute from it😋 
When working with this script don't forget about right permissions (40777)!

**Comment by zanix** [comment]
That would surely do it, glad you figured it out!
