### ISSUE TITLE
overviewer.py

### ISSUE THREAD

**Issue by sheldontking** [MinecraftServerControl/mscs#316]
/usr/bin/which: no overviewer.py in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)

Rocky Linux 8

All attempts to get it installed have failed even by manual source compile. Documentation update requested.

**Comment by zanix** [comment]
Overviewer is an external tool that is not installed as part of MSCS.
The instructions to install Overviewer are on their site: http://docs.overviewer.org/en/latest/installing/

**Comment by sandain** [comment]
@sheldontking, we are going to need more info on what you have tried and what errors you are getting if you want our help. As @zanix mentioned, Overviewer is just a mapping tool that MSCS can use if you have it installed. This is not something that we would normally support, but we may be able to help if you give us something to work with
