### ISSUE TITLE
Can't join my server

### ISSUE THREAD

**Issue by Samoht1** [MinecraftServerControl/mscs#317]
My Paper server launched without any seeming problems in the logs. But when I try to connect on my client I get a error message I don't understand: 
![image](https://user-images.githubusercontent.com/15867250/184256254-41be1f53-7d83-47c4-a07a-62daccadff03.png)

Please help

**Comment by sandain** [comment]
Do the logs give any more information after you try connecting? I've never seen this error, and I'm not seeing any references to it on the internet.

**Comment by Samoht1** [comment]
No it seemed to start and run just fine, no errors

**Comment by zanix** [comment]
This is the only reference to this error I have found from Google
https://www.spigotmc.org/threads/cant-connect-to-new-server-return-value-of-java-util-map-get-object-is-null.569250/

From the post:

> Edit2: Issue was resolved after using apt to purge all java* packages, using apt with --fix-broken install, and reinstalling default-jre, then rerunning java -jar BuildTools.jar.

**Comment by Samoht1** [comment]
without any solution sadly... I just reinstalled the server and now it works just fine

**Comment by zanix** [comment]
Glad it's working, once again proving this solution works
https://youtu.be/nn2FB1P_Mn8?t=11
