### ISSUE TITLE
Error downloading version manifest (due to change of the version manifest url?)

### ISSUE THREAD

**Issue by Latuchi** [MinecraftServerControl/mscs#318]
During the summer they changed the URL for version manifest and recently I've not been able to download the version manifest with mscs. Error also leads to not being able to update the server with mscs, downloading the version manifest by hand didn't seem to do anything. I also receive this malformed JSON string error.
`malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at -e line 14, <> chunk 1.` 

This could be related? https://bugs.mojang.com/browse/WEB-5905

**Comment by sandain** [comment]
Hi @Latuchi.

I just gave the update function a try, and it worked just fine.
```
$ sudo mscs status
Minecraft Server Status:
  alpha: running version 1.19 (0 of 20 users online).
    Port: 25566.
    Memory used: 1.37GB (2GB allocated).
    Process ID: 2581.
    Crash Monitor PID: 3954
$ sudo rm /opt/mscs/version_manifest.json /opt/mscs/version_manifest.json.bak
$ sudo mscs update
Downloading current Minecraft version manifest.
Stopping Minecraft Server: alpha.
Backing up Minecraft Server: alpha.
Updating Server Software: alpha.
Restarting Minecraft Server: alpha.
$ sudo mscs status
Minecraft Server Status:
  alpha: running version 1.19.2 (0 of 20 users online).
    Port: 25566.
    Memory used: 1.79GB (2GB allocated).
    Process ID: 62308.
    Crash Monitor PID: 62434
```

Try removing the `version_manifest.json` as I did above and see if that works for you.
```
 sudo rm /opt/mscs/version_manifest.json /opt/mscs/version_manifest.json.bak
```

Check that permissions are correct if that doesn't work.
```
sudo chmod -R u+w /opt/mscs
sudo chown -R minecraft:minecraft /opt/mscs
```

**Comment by Latuchi** [comment]
Thanks for the help @sandain 🙂
Seems like yesterday there was some weird dhcp issue at the data center I have my server at as today `mscs update` worked just fine without any issues.
