### ISSUE TITLE
[Question] quilt compatibility?

### ISSUE THREAD

**Issue by Fauli1221** [MinecraftServerControl/mscs#324]
Is it possible to run a quiltmc server with mscs?

**Comment by zanix** [comment]
This seems like it would be similar to using [Forge in MSCS](https://minecraftservercontrol.github.io/docs/mscs/adjusting-world-server-properties/forge)
Forge uses an installer and it looks like Quilt does as well.

> Please note that I did not test this and is my best guess on how to make Quilt work!

Download the Quilt installer and run.

> Replace `{INSTALLER_VERSION}`, `{MINECRAFT_VERSION}` as needed.

```shell
mkdir -p /opt/mscs/server/quilt-{MINECRAFT_VERSION}
cd /opt/mscs/server/quilt-{MINECRAFT_VERSION}
wget {URL_TO_QUILT_INSTALLER}
java -jar quilt-installer-{INSTALLER_VERSION}.jar \
  install server {MINECRAFT_VERSION} \
  --download-server
```

Then it should be similar to the [Forge 1.16.5](https://minecraftservercontrol.github.io/docs/mscs/adjusting-world-server-properties/forge#forge-1165-and-before) instructions.

> Replace `{PORT}` with the next available server port.

```shell
mscs create quilt {PORT}
editor /opt/mscs/worlds/quilt/mscs.properties
```

Add this

```ini
mscs-client-version={MINECRAFT_VERSION}
mscs-server-version={MINECRAFT_VERSION}
mscs-server-jar=quilt-{MINECRAFT_VERSION}/quilt-server-launch.jar
mscs-server-url=
```

And save

**Comment by zanix** [comment]
Added QuiltMC to docs
https://minecraftservercontrol.github.io/docs/mscs/adjusting-world-server-properties/quiltmc

I did not check this myself, it's based on the conversation above

**Comment by nolanbarry** [comment]
After running through the setup, I couldn't get my server to launch. `<world_path>/console.out` reports:
```
The Minecraft server .JAR is missing (/opt/mscs/worlds/quilt-server/server.jar)!

Quilt's server-side launcher expects the server .JAR to be provided.
You can edit its location in quilt-server-launcher.properties.

Without the official Minecraft server .JAR, Quilt Loader cannot launch.
Exception in thread "main" java.lang.RuntimeException: Failed to setup Quilt server environment!
	at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:60)
Caused by: java.lang.RuntimeException: Missing game jar at /opt/mscs/worlds/quilt-server/server.jar
	at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.setup(QuiltServerLauncher.java:86)
	at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:58)
```
So I went ahead and modified `/opt/mscs/worlds/quilt-server/quilt-server-launcher.properties` with the path to the regular server jar:
```
serverJar=/opt/mscs/server/minecraft_server.1.20.1.jar
```
I'm not sure if maybe it'd of been better to copy the jar into my world folder and point the path there but this seems to work fine.
