### ISSUE TITLE
Purge old backups?

### ISSUE THREAD

**Issue by eric-sabe** [MinecraftServerControl/mscs#327]
Is there a recommended way to purge backups older than x days?  Trying to save money on my cloud storage bill.  :)

**Comment by zanix** [comment]
You can set `mscs-backup-duration` in `/opt/mscs/mscs.defaults`
This is the length in days that backups survive. A value less than 1 disables backup deletion. The default is 15.

Backups are cleaned up whenever you run the backup command based on the duration set in `mscs.defaults`.


If you want to manually trim old backups, you can run the following:

```shell
rdiff-backup --remove-older-than 15D --force /opt/mscs/backups/WORLD
```
Replace `15` with the number of days to trim
Replace `WORLD` with the world you want to trim the backups for

More info about backups: https://minecraftservercontrol.github.io/docs/mscs/backups
More info about `mscs.defaults`: https://minecraftservercontrol.github.io/docs/mscs/adjusting-world-server-properties

**Comment by zanix** [comment]
I just noticed the backup cleanup was split off the main backup function, maybe this can be exposed as a command option.

**Comment by zanix** [comment]
Added a PR to expose this function as `clean-backups`
