### ISSUE TITLE
Permissions denied when executing mscs commands

### ISSUE THREAD

**Issue by aidan-walden** [MinecraftServerControl/mscs#330]
Note that the error does not prevent the command from successfully executing. For example, executing `mscs start <world>` will work and start the server, but the error still appears

`find: Failed to restore initial working directory: /home/aidan: Permission denied`

I have already run these commands found in the troubleshooting guide:
```
chmod -R u+w /opt/mscs
chown -R minecraft:minecraft /opt/mscs
```

I have attached my mscs.properties and mscs.defaults
[mscs.defaults.txt](https://github.com/MinecraftServerControl/mscs/files/11938771/mscs.defaults.txt)
[mscs.properties.txt](https://github.com/MinecraftServerControl/mscs/files/11938772/mscs.properties.txt)

**Comment by zanix** [comment]
It could be that the minecraft user doesn't have permission to view `/home/aidan`. Try changing to a different directory before running `mscs` (like `/home` or `/opt`)
