### ISSUE TITLE
Overviewer is No Longer Maintained

### ISSUE THREAD

**Issue by zanix** [MinecraftServerControl/mscs#333]
It looks like [Overviewer is dead](https://github.com/overviewer/Minecraft-Overviewer) and currently doesn't work for version 1.20.

> PLEASE NOTE: Overviewer is currently unmaintained. PRs will not be merged and issues will not be addressed. The website and repository will remain online and accessible.

However, someone [forked it](https://github.com/GregoryAM-SP/The-Minecraft-Overviewer) and is currently working on updates.

We should probably update the documentation to point to the new GitHub repo.

**Comment by sandain** [comment]
Another option is [BlueMap](https://bluemap.bluecolored.de/)

**Comment by alexangas** [comment]
Let me know in the PR if the text is no good or you want to take a different approach.

I created a new issue for supporting BlueMap in #338.
