### ISSUE TITLE
Add Configuratrion Setting to disable AutoStart or Start on boot up  of minecraft servers (different then disable world)

### ISSUE THREAD

**Issue by OneWeekNotice** [MinecraftServerControl/mscs#340]
Hello,

Would it be a good use case to add AutoStart/ Start on boot up configuration option

Use case: For minecraft worlds that you want enabled BUT do not want to start on the boot up of the computer. This is a very specific use case for [mcsleepingserverstarter](https://github.com/vincss/mcsleepingserverstarter) (which in combination will use [mcEmptyServerStopper](https://github.com/vincss/mcEmptyServerStopper))

These two services will start and stop the minecraft server to save power and resources. One of the prerequisite of  mcsleepingserverstarter is to ensure you server is stopped so it can start it when a initial connection is meant

> 1. Download binarie  corresponding to your OS
> 2. Place the executable in the same folder as your server file (spigot.jar, paper.jar, etc...)
> 3. Make sure your server is stopped
> 4. Run the executable
> 5. On Linux, try chmod +x mcsleepingserverstarter-linux-x64 if you can't run the executable

Currently this is not possible with the combination of mscs since it auto boots the server on start of the computer. 

I understand that this is a very specific use case and most people would want there minecraft servers to start on boot which is understandable if this is not a priority of this project

Thanks for the read

**Comment by zanix** [comment]
Take a look at [this discussion](https://github.com/MinecraftServerControl/mscs/discussions/332#discussioncomment-6993552).
The gist is that you disable global autostart and create an autostart for each world you want to autostart.

**Comment by OneWeekNotice** [comment]
Thank you very much!
