### ISSUE TITLE
Error when launching a server with Forge installed

### ISSUE THREAD

**Issue by rasmuand** [MinecraftServerControl/mscs#346]
i just installed mscs this morning, and i can start up a vanilla server just fine.  but after installing the latest Forge installer (1.21.1-52.0.9) i get the error message "Error starting the server: couldn't retrieve the server's process ID."  i followed the instructions listed at https://minecraftservercontrol.github.io/docs/mscs/adjusting-world-server-properties/forge.

output of console.out:
`Error: Unable to access jarfile forge-1.21.1-52.0.9-shim.jar`

contents of mscs.properties:
```
mscs-enabled=true
mscs-client-version=1.21.1
mscs-server-version=1.21.1
mscs-server-command=/opt/mscs/server/forge-1.21.1-52.0.9/run.sh
```
if i comment out the client version, server version, and server command lines, the server will start up normally, although with no mods installed.

i double checked the run.sh file located at /opt/mscs/server/forge-1.21.1-52.0.9:
```
#!/usr/bin/env sh
# Add custom JVM arguments (such as RAM allocation) to the user_jvm_args.txt

java -jar /opt/mscs/server/forge-1.21.1-52.0.9/forge-1.21.1-52.0.9-shim.jar --onlyCheckJava || exit 1

# Add custom program arguments (such as nogui) to the next line before the --nogui "$@" or pass them to this script directly
java @/opt/mscs/server/forge-1.21.1-52.0.9/user_jvm_args.txt @/opt/mscs/server/forge-1.21.1-52.0.9/libraries/net/minecraftforge/forge/1.21.1-52.0.9/unix_args.txt --nogui "$@"
```
it originally just had the relative path for the shim file, but i added the absolute path when troubleshooting, with no change.  is there a typo i'm missing somewhere?  the mods folder is currently empty, i wanted to get the server functioning before adding any mods.  i'm running Java 21, verified by running java -version:
openjdk version "21.0.4" 2024-07-16
OpenJDK Runtime Environment (build 21.0.4+7-Ubuntu-1ubuntu224.04)
OpenJDK 64-Bit Server VM (build 21.0.4+7-Ubuntu-1ubuntu224.04, mixed mode, sharing)

**Comment by rasmuand** [comment]
this is running Ubuntu 24.04 inside a proxmox VM, if that makes any difference.

**Comment by sandain** [comment]
Hi @rasmuand.  Everything looks correct from this end, but I could be missing something too.  

Let's start with the error message though. Please verify that the jar file is there and that your minecraft user has read access:
```
ls -la /opt/mscs/server/forge-1.21.1-52.0.9/forge-1.21.1-52.0.9-shim.jar
```

Now check as the minecraft user if you can run the jar file:
```
sudo su -s /bin/bash minecraft
java -jar /opt/mscs/server/forge-1.21.1-52.0.9/forge-1.21.1-52.0.9-shim.jar --onlyCheckJava || exit 1
```

I'd also like to see the contents of `/opt/mscs/server/forge-1.21.1-52.0.9/user_jvm_args.txt` and `/opt/mscs/server/forge-1.21.1-52.0.9/libraries/net/minecraftforge/forge/1.21.1-52.0.9/unix_args.txt`.

**Comment by rasmuand** [comment]
/opt/mscs/server/forge-1.21.1-52.0.9/libraries/net/minecraftforge/forge/1.21.1-52.0.9/unix_args.txt was the culprit.  it was originally
 `-Djava.net.preferIPv6Addresses=system -jar forge-1.21.1-52.0.9-shim.jar`
after changing it to 
`-Djava.net.preferIPv6Addresses=system -jar /opt/mscs/server/forge-1.21.1-52.0.9/forge-1.21.1-52.0.9-shim.jar`
it's now working.
