### ISSUE TITLE
Issue importing a server previously hosted with essential

### ISSUE THREAD

**Issue by MeBePerson** [MinecraftServerControl/mscs#350]
I had a friend who hosted a small modded server over essential, which quickly became more popular than his PC or wallet could handle, so I took on the task of setting up a dedicated server. I had MSCS already installed and decided to use that, but whenever I tried to import the files he sent me it would always give me the "directory containing a minecraft  world was not provided" error, and I've been tearing my hair out trying to fix it. Any help would be appreciated, thanks.
(also please ignore the poor crop on the image)
![eror](https://github.com/user-attachments/assets/8ea80d31-c0de-4433-a368-d42d5b1b8d2e)

**Comment by zanix** [comment]
I believe you need to go up a directory (`/home/****/pokemon`)

**Comment by MeBePerson** [comment]
I've tried that to no difference, but thanks

**Comment by zanix** [comment]
Could you post a directory listing of `/home/****/pokemon`?

Also, I wonder if path expansion doesn't work on that command, have you tried:

```shell
mscs import /home/****/pokemon pokemon 25565
```

**Comment by MeBePerson** [comment]
Sorry I didn't respond sooner, the contents of /pokemon are just the zip file of the server my friend sent me and the folder /Pokemon, which contains what was listed in the first image. Also I tried that command to nothing different

**Comment by zanix** [comment]
If there is only the zip file, you are missing a few files. You only copied over the world data directory.
The `/home/****/pokemon` directory should look like this:

```
crash-reports/
libraries/
logs/
Pokemon/
banned-ips.json
banned-players.json
crash-reports/
logs/
ops.json
server.properties
usercache.json
whitelist.json
```

Once you get these files in place, try to import again.
After that, you might want to create a `mscs.properties` file for this server
https://minecraftservercontrol.github.io/docs/mscs/adjusting-world-server-properties#individual-world-properties

Depending on the server type, you might need something like this:

```ini
mscs-client-version=1.16.4
mscs-server-version=1.16.4
mscs-server-jar=forge-1.16.4-35.1.7/forge-1.16.4-35.1.7.jar
mscs-server-url=
```

**Comment by zanix** [comment]
If you run into issues again just let me know!

**Comment by MeBePerson** [comment]
Sorry I didn't respond sooner, I managed to get a few more files from my friend and with a lot of trial and error and only one casualty (lost one mod to an actually unique glitch) I managed to get it working, and it runs way better than when it was on an old laptop. Thank you so much for the help!

**Comment by zanix** [comment]
Awesome! I'm happy that it works and glad I could help!
