### ISSUE TITLE
Backing up a Fabric server while it's running results in world specific files being skipped

### ISSUE THREAD

**Issue by T3mp3lis** [MinecraftServerControl/mscs#351]
It appears to be only backing up the original state of the world, but not the player-made changes to it, although the backup of player state is completed as expected. 
![image](https://github.com/user-attachments/assets/80b3182b-0f3e-4bb4-9472-6a26723c7c2a)

**Comment by zanix** [comment]
I'm not sure what that software is, but it's not MSCS.
This looks like [MC Server Soft](https://mcserversoft.com/)

**Comment by T3mp3lis** [comment]
> I'm not sure what that software is, but it's not MSCS. This looks like [MC Server Soft](https://mcserversoft.com/)

god damn I am an idiot, sorry about that

**Comment by zanix** [comment]
> > I'm not sure what that software is, but it's not MSCS. This looks like [MC Server Soft](https://mcserversoft.com/)
> 
> god damn I am an idiot, sorry about that

It's all good. I hope you solve your issue.
